Repository bedita/manager, pull requests merged in 2018-12, with the labels that each got.

#232 Tests/new test cases
  src/Controller/AppController.php
  tests/TestCase/Controller/AppControllerTest.php
  tests/TestCase/Controller/DashboardControllerTest.php
Labels: Priority - Normal, feature

#218 Issue/203 list object filter
  package.json
  src/Controller/Component/PropertiesComponent.php
  src/Controller/ModelController.php
  src/Controller/ModulesController.php
  src/Core/Utility/Form.php
  src/Template/Element/Form/relation.twig
  src/Template/Element/Form/relations.scss
  src/Template/Element/Toolbar/filters.scss
  src/Template/Element/Toolbar/filters.twig
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/filter-box.js
  src/Template/Layout/js/app/components/input-dynamic-attributes.js
  src/Template/Layout/js/app/directives/jsoneditor.js
  tests/TestCase/Controller/Component/PropertiesComponentTest.php
  tests/TestCase/Core/Utility/FormTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
  webroot/css/style.css
  webroot/js/app.bundle.js
  webroot/js/vendors.bundle.js
  yarn.lock
Labels: Priority - High, feature

#205 Issue/192 model property
  composer.json
  config/routes.php
  package.json
  src/Controller/ModelController.php
  src/Template/Element/Toolbar/filters.twig
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/autosize-textarea.js
  src/Template/Layout/js/app/components/filter-box.js
  src/Template/Layout/js/app/components/relation-view/relation-view.js
  src/Template/Layout/js/app/components/tree-view/tree-view.js
  src/Template/Layout/js/app/directives/datepicker.js
  src/Template/Layout/js/app/directives/jsoneditor.js
  src/Template/Layout/js/app/directives/richeditor.js
  src/Template/Layout/js/app/pages/model/index.js
  src/Template/Layout/js/app/pages/modules/index.js
  src/Template/Layout/js/app/pages/trash/index.js
  src/Template/Layout/styles/_forms.scss
  src/Template/Pages/Model/_model-index.scss
  src/Template/Pages/Model/index.twig
  tests/TestCase/Controller/ModelControllerTest.php
  webroot/css/be-icons-codes.css
  webroot/css/style.css
  webroot/css/vendors.css
  webroot/js/app.bundle.js
  webroot/js/manifest.bundle.js
  webroot/js/vendors.bundle.js
  yarn.lock
Labels: feature

#238 fix: failing test on user token
  tests/TestCase/Controller/AppControllerTest.php
Labels: Priority - High, bug

#241 Issue/239 filter box boolean
  src/Template/Element/Toolbar/filters.scss
  src/Template/Layout/js/app/components/filter-box.js
  src/Template/Layout/js/app/components/input-dynamic-attributes.js
  webroot/css/style.css
  webroot/js/app.bundle.js
Labels: Priority - Normal, feature

#248 Fix/other properties
  src/Controller/Component/PropertiesComponent.php
  src/Template/Element/Form/other_properties.twig
  tests/TestCase/Controller/Component/PropertiesComponentTest.php
Labels: Priority - Critical, bug

#245 Tests/new test cases
  tests/TestCase/Controller/Component/ModulesComponentTest.php
  tests/TestCase/Controller/ErrorControllerTest.php
  tests/TestCase/Controller/ModelControllerTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
Labels: Priority - Low, feature

#247 Issue/244 new media from side panel
  config/routes.php
  src/Controller/ModulesController.php
  src/Template/Element/Form/relations.scss
  src/Template/Element/panel.twig
  src/Template/Layout/js/app/components/relation-view/relations-add.js
  tests/TestCase/Controller/ModulesControllerTest.php
  webroot/css/style.css
  webroot/js/app.bundle.js
Labels: Priority - High, feature
