Repository bedita/manager, pull requests merged in 2019-01, with the labels that each got.

#259 #258 fix: model View
  config/schema_properties.php
  src/View/Helper/SchemaHelper.php
Labels: bug

#261 Issue/253 create new media
  src/Template/Element/panel.twig
  src/Template/Layout/js/app/components/relation-view/relations-add.js
  webroot/js/app.bundle.js
Labels: Priority - Normal, bug

#262 Issue/251 view media
  src/Template/Element/Form/relation.twig
  src/Template/Element/Form/relations.scss
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/helpers/download.js
  src/Template/Layout/js/app/pages/modules/view.js
  src/Template/Pages/Modules/_modules-view.scss
  src/Template/Pages/Modules/view.twig
  webroot/css/style.css
  webroot/js/app.bundle.js
  webroot/js/vendors.bundle.js
Labels: Priority - Normal, feature

#264 Fix `other` properties display
  src/Controller/Component/PropertiesComponent.php
  tests/TestCase/Controller/Component/PropertiesComponentTest.php
Labels: Priority - Critical, bug

#263 Fix/thumbs and download button + panel url
  src/Template/Element/Form/children.twig
  src/Template/Element/Form/relation.twig
  src/Template/Element/Form/relations.scss
  src/Template/Element/panel.twig
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/helpers/view.js
  src/Template/Pages/Modules/view.twig
  webroot/css/style.css
  webroot/js/app.bundle.js
Labels: Priority - Normal, bug

#260 Feat/webpack feature
  README.md
  config/.env.default
  package.json
  webpack.config.environment.js
  webpack.config.js
  yarn.lock
Labels: Priority - Low, feature
