Repository bedita/manager, pull requests merged in 2021-11, with the labels that each got.

#634 Roles save and remove
  src/Controller/Admin/AdministrationBaseController.php
  src/Controller/Admin/RolesController.php
  src/Template/Element/Admin/index_content.twig
  tests/TestCase/Controller/Admin/AdministrationBaseControllerTest.php
  tests/TestCase/Controller/Admin/RolesControllerTest.php
Labels: feature, Priority - Normal

#637 Application name in history box
  src/Controller/Component/HistoryComponent.php
  src/Controller/Component/ProjectConfigurationComponent.php
  src/Controller/Component/SchemaComponent.php
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Locale/master.pot
  src/Template/Layout/js/app/components/history/history.js
  src/Utility/Applications.php
  src/Utility/CacheTools.php
  tests/TestCase/Controller/Component/HistoryComponentTest.php
  tests/TestCase/Controller/Component/ProjectConfigurationComponentTest.php
  tests/TestCase/Controller/Component/SchemaComponentTest.php
  tests/TestCase/Utility/ApplicationsTest.php
  tests/TestCase/Utility/CacheToolsTest.php
Labels: feature, Priority - Normal

#638 feat - Relations filters
  src/Controller/Component/PropertiesComponent.php
  src/Controller/ModulesController.php
  src/Template/Element/FilterBox/filter_box.scss
  src/Template/Element/FilterBox/filter_box_common.twig
  src/Template/Element/FilterBox/filter_box_page_toolbar.twig
  src/Template/Element/Form/relation.twig
  src/Template/Element/Modules/index_header.twig
  src/Template/Element/Panel/relations_add.twig
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/filter-box.js
  src/Template/Layout/js/app/components/relation-view/relation-view.js
  src/Template/Layout/js/app/components/relation-view/relations-add.js
  src/Template/Layout/js/app/mixins/paginated-content.js
  src/Template/Layout/js/config/config.js
  src/Template/Layout/js/libs/filters.js
  src/Template/Layout/js/libs/urlUtils.js
  tests/TestCase/Controller/Component/PropertiesComponentTest.php
Labels: feature, Priority - Normal

#639 Categories tree in object view
  src/Controller/Component/SchemaComponent.php
  src/Template/Element/Form/categories.scss
  src/Template/Element/Form/categories.twig
  src/View/AppView.php
  src/View/Helper/CategoriesHelper.php
  tests/TestCase/Controller/Component/SchemaComponentTest.php
  tests/TestCase/View/Helper/CategoriesHelperTest.php
Labels: feature, Priority - Normal

#641 Eslint in GH action
  .eslintrc.js
  .eslintrc.json
  .github/workflows/javascript.yml
  package.json
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/date-input.js
  src/Template/Layout/js/app/components/date-ranges-view/date-ranges-view.js
  src/Template/Layout/js/app/components/dialog/dialog.js
  src/Template/Layout/js/app/components/drop-upload.js
  src/Template/Layout/js/app/components/map-view.js
  src/Template/Layout/js/app/components/menu.js
  src/Template/Layout/js/app/components/panel-view.js
  src/Template/Layout/js/app/components/property-view/property-view.js
  src/Template/Layout/js/app/components/relation-view/relations-add.js
  src/Template/Layout/js/app/components/relation-view/relationships-view/relationships-view.js
  src/Template/Layout/js/app/components/relation-view/resource-relation-view.js
  src/Template/Layout/js/app/components/tree-view/tree-view.js
  src/Template/Layout/js/app/directives/richeditor.js
  src/Template/Layout/js/app/helpers/api-translation.js
  src/Template/Layout/js/app/helpers/download.js
  src/Template/Layout/js/app/helpers/view.js
  src/Template/Layout/js/app/mixins/dragdrop.js
  src/Template/Layout/js/app/mixins/observable.js
  src/Template/Layout/js/app/pages/dashboard/index.js
  src/Template/Layout/js/app/pages/import/index.js
  src/Template/Layout/js/app/pages/model/index.js
  src/Template/Layout/js/app/pages/modules/view.js
  src/Template/Layout/js/config/config.js
  src/Template/Layout/js/libs/filters.js
  webpack.config.js
  yarn.lock
Labels: feature, Priority - Normal

#643 Update README.md
  README.md
Labels: feature, Priority - Low

#644 Fix show fastCreate form on type change
  src/Template/Element/Panel/relations_add.twig
Labels: bug, Priority - High

#647 Fix missing model-type in fast create media form
  src/Template/Layout/js/app/components/relation-view/relations-add.js
Labels: bug, Priority - High

#650 Admin applications: insert, modify and delete [no api key]
  src/Controller/Admin/AdministrationBaseController.php
  src/Controller/Admin/ApplicationsController.php
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Locale/master.pot
  src/Template/Element/Admin/index_content.twig
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/pages/admin/index.js
  tests/TestCase/Controller/Admin/AdministrationBaseControllerTest.php
Labels: feature, Priority - Normal

#653 Add CHANGES.md
  CHANGES.md
Labels: Priority - Normal, documentation
