Repository bedita/manager, pull requests merged in 2022-08, with the labels that each got.

#828 Recovery mode
  config/app_local.example.php
  src/Application.php
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Middleware/RecoveryMiddleware.php
  src/Template/Element/custom_colors.twig
  src/Template/Layout/default.twig
  tests/TestCase/Middleware/RecoveryMiddlewareTest.php
Labels: feature, Priority - Normal

#825 Tag picker tag label and name
  src/Template/Layout/js/app/components/tag-picker/tag-picker.js
Labels: feature, Priority - Normal, UI / UX, javascript

#831 Feat/media detail layout
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Template/Element/Form/media.twig
  src/Template/Element/Form/upload.twig
  src/Template/Layout/styles/_utility_classes.scss
Labels: feature, Priority - Normal, UI / UX

#822 Login via external OAuth2 provider
  composer.json
  config/app.php
  config/app_local.example.php
  config/routes.php
  src/Application.php
  src/Controller/LoginController.php
  src/Identifier/ApiIdentifier.php
  src/Identifier/Resolver/ApiResolver.php
  src/Template/Pages/Login/login.twig
  tests/TestCase/ApplicationTest.php
  tests/TestCase/Authentication/Identifier/ApiIdentifierTest.php
  tests/TestCase/Authentication/Identifier/Resolver/ApiResolverTest.php
  tests/TestCase/Controller/AppControllerTest.php
  tests/TestCase/Controller/LoginControllerTest.php
  tests/TestCase/Middleware/RecoveryMiddlewareTest.php
Labels: feature

#827 Use php-cs-stan-unit reusable workflow
  .github/workflows/php.yml
  composer.json
  phpcs.xml.dist
Labels: feature, Priority - Normal, refactor

#829 Index pages: highlight selected and hover + index-cell
  config/app_local.example.php
  src/Template/Element/Modules/index_table_row.twig
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/index-cell/index-cell.js
  src/Template/Layout/js/app/pages/modules/index.js
  src/Template/Layout/style.scss
  src/Template/Pages/Modules/_modules-index.scss
  src/Template/Pages/Translations/index.scss
Labels: feature, Priority - Normal, UI / UX, javascript
