Repository bedita/manager, pull requests merged in 2022-11, with the labels that each got.

#876 Add docker image creation on release workflow
  .github/workflows/release.yml
  Dockerfile
Labels: feature

#871 Use `manifest.json` instead of folder scan for css/js bundle links
  .gitignore
  package.json
  src/View/Helper/LinkHelper.php
  tests/TestCase/View/Helper/LinkHelperTest.php
  tests/files/manifest.json
  webpack.config.js
  yarn.lock
Labels: refactor, release:patch

#873 Fix object types associations as empty string
  src/Controller/Model/ObjectTypesController.php
  tests/TestCase/Controller/Model/ObjectTypesControllerTest.php
Labels: bug, release:patch

#878 Remove deprecations and check via PHPStan
  composer.json
  src/Controller/Admin/CacheController.php
  src/Core/Filter/ImportFilter.php
Labels: integration

#881 Node 18.x in javascript workflow
  .github/workflows/javascript.yml
Labels: integration

#879 Tags module
  config/app.php
  config/routes.php
  resources/js/app/app.js
  resources/js/app/components/tag-form/tag-form.js
  resources/js/app/components/tag-form/tag-form.scss
  resources/js/app/pages/model/index.js
  resources/style.scss
  src/Controller/Component/HistoryComponent.php
  src/Controller/Component/ModulesComponent.php
  src/Controller/Component/SchemaComponent.php
  src/Controller/Model/ModelBaseController.php
  src/Controller/Model/TagsController.php
  src/Controller/TagsController.php
  src/Core/Filter/ReadCSVTrait.php
  src/View/Helper/LayoutHelper.php
  templates/Element/Modules/index_tags.twig
  templates/Pages/Model/PropertyTypes/index.twig
  templates/Pages/Model/Tags/index.twig
  tests/TestCase/Controller/Component/ModulesComponentTest.php
  tests/TestCase/Controller/Component/SchemaComponentTest.php
  tests/TestCase/Controller/Model/ModelBaseControllerTest.php
  tests/TestCase/Controller/Model/ModelTagsControllerTest.php
  tests/TestCase/Controller/TagsControllerTest.php
Labels: feature, Priority - Normal, UI / UX, release:patch

#884 Fix user profile change password
  src/Controller/UserProfileController.php
  templates/Pages/UserProfile/view.twig
  tests/TestCase/Controller/UserProfileControllerTest.php
Labels: bug, Priority - High, release:patch

#885 Fix reset password
  src/Controller/PasswordController.php
Labels: bug, Priority - Normal, release:patch

#886 Tags module permissions
  resources/js/app/components/tag-form/tag-form.js
  src/Controller/Component/ModulesComponent.php
  src/Controller/TagsController.php
  templates/Element/Modules/index_tags.twig
Labels: feature, Priority - High, release:patch

#889 Bump vue-loader to 15.10.0 (and loader-utils to 1.4.1)
  yarn.lock
Labels: Priority - High, dependencies, javascript, release:patch

#887 Meta, title and BEdita references updates
  README.md
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  phpunit.xml.dist
  resources/richeditor.lazy.scss
  resources/style.scss
  src/Controller/ApiController.php
  templates/Element/Menu/sidebar.twig
  templates/Element/meta.twig
  templates/Layout/default.twig
  templates/Layout/error.twig
  tests/TestCase/Middleware/StatusMiddlewareTest.php
Labels: feature, Priority - Normal

#890 Bump socket.io-parser to 4.0.5
  yarn.lock
Labels: Priority - Normal, dependencies, javascript, release:patch

#891 Bump loader-utils to 2.0.4
  yarn.lock
Labels: Priority - Normal, dependencies, javascript, release:patch

#894 Bump enging.io to 6.2.1
  yarn.lock
Labels: Priority - High, dependencies, javascript

#895 Bump loader-utils to 1.4.2
  yarn.lock
Labels: Priority - High, dependencies, javascript

#880 Fix json editor save
  resources/js/app/components/json-editor-input.js
  src/Controller/AppController.php
  tests/TestCase/Controller/AppControllerTest.php
Labels: bug, Priority - Normal, javascript, release:patch

#896 Fix `modified_by` meta display
  resources/js/app/components/property-view/property-view.js
Labels: bug, release:patch

#897 Buttons UI in admin
  templates/Element/Admin/index_content.twig
  templates/Element/Admin/sidebar.twig
  templates/Pages/Admin/Appearance/index.twig
  templates/Pages/Admin/RolesModules/index.twig
Labels: feature, Priority - Normal, UI / UX
