Repository bedita/manager, pull requests merged in 2022-02, with the labels that each got.

#687 Fix Properties component
  src/Controller/Component/PropertiesComponent.php
  tests/TestCase/Controller/Component/PropertiesComponentTest.php
Labels: bug

#668 update functions signature with return type
  src/Application.php
  src/Console/Installer.php
  src/Controller/AppController.php
  src/Controller/Component/FlashComponent.php
  src/Controller/Component/HistoryComponent.php
  src/Controller/Component/ModulesComponent.php
  src/Controller/Component/SchemaComponent.php
  src/Controller/Component/TranslatorComponent.php
  src/Controller/ImportController.php
  src/Controller/PasswordController.php
  src/Controller/UserProfileController.php
  src/Core/Filter/ImportFilter.php
  src/Core/Result/ImportResult.php
  src/Core/Result/Result.php
  src/Form/Form.php
  src/Shell/ConsoleShell.php
  src/View/AppView.php
  src/View/Helper/LinkHelper.php
  tests/TestCase/ApplicationTest.php
  tests/TestCase/Controller/Component/CategoriesComponentTest.php
  tests/TestCase/Controller/Component/ExportComponentTest.php
  tests/TestCase/Controller/Component/FlashComponentTest.php
  tests/TestCase/Controller/Component/ModulesComponentTest.php
  tests/TestCase/Controller/Component/QueryComponentTest.php
  tests/TestCase/Controller/Component/SchemaComponentTest.php
  tests/TestCase/Controller/Component/ThumbsComponentTest.php
  tests/TestCase/Controller/Component/TranslatorComponentTest.php
  tests/TestCase/Controller/ExportControllerTest.php
  tests/TestCase/Controller/ImportControllerTest.php
  tests/TestCase/Controller/LockControllerTest.php
  tests/TestCase/Controller/Model/PropertyTypesControllerTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
  tests/TestCase/Controller/PasswordControllerTest.php
  tests/TestCase/Controller/TranslationsControllerTest.php
  tests/TestCase/Controller/TranslatorControllerTest.php
  tests/TestCase/Controller/TrashControllerTest.php
  tests/TestCase/Core/Filter/ImportFilterTest.php
  tests/TestCase/Core/Filter/ReadCSVTraitTest.php
  tests/TestCase/Core/Result/ImportResultTest.php
  tests/TestCase/Core/Result/ResultTest.php
  tests/TestCase/PluginTest.php
  tests/TestCase/Utility/OEmbedTest.php
  tests/TestCase/View/Helper/ArrayHelperTest.php
  tests/TestCase/View/Helper/CalendarHelperTest.php
  tests/TestCase/View/Helper/CategoriesHelperTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: feature, Priority - Normal

#688 fix: bulk position labels click
  src/Template/Element/Form/bulk_position.twig
  src/Template/Layout/styles/_forms.scss
  yarn.lock
Labels: bug, Priority - Normal

#690 Bump node-fetch to 2.6.7
  yarn.lock
Labels: Priority - High, dependencies

#693 Texts translations enhancements [not about Translation objects]
  config/i18n_strings.php
  src/Form/Form.php
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Locale/master.pot
  src/Template/Element/Form/locations.twig
  src/Template/Element/Form/other_properties.twig
  src/Template/Element/Form/related_item.twig
  src/Template/Element/Form/related_translations.twig
  src/Template/Element/Form/relation.twig
  src/Template/Element/Form/relations.twig
  src/Template/Element/Form/resource_relations.twig
  src/Template/Element/Form/roles.twig
  src/Template/Element/Form/trees.twig
  src/Template/Element/Menu/menu.twig
  src/Template/Element/Modules/index_table_header.twig
  src/Template/Element/Modules/index_table_row.twig
  src/Template/Element/Panel/relations_add.twig
  src/Template/Element/filter_type.twig
  src/Template/Layout/js/app/components/edit-relation-params.js
  src/Template/Layout/js/app/components/locations-view/location-view.js
  src/Template/Layout/js/app/components/locations-view/locations-view.js
  src/Template/Layout/js/app/components/relation-view/relation-view.js
  src/Template/Layout/js/app/components/relation-view/relations-add.js
  src/Template/Layout/js/app/components/relation-view/relationships-view/relationships-view.js
  src/Template/Layout/js/app/components/relation-view/resource-relation-view.js
  src/Template/Layout/js/app/components/tree-view/tree-view.js
  src/Template/Layout/js/libs/bedita.js
  src/Template/Pages/Dashboard/index.twig
  src/Template/Pages/Trash/view.twig
  src/Utility/Translate.php
  src/View/Helper/LayoutHelper.php
  src/View/Helper/PropertyHelper.php
  tests/TestCase/Form/FormTest.php
  tests/TestCase/Utility/TranslateTest.php
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: feature, Priority - Normal

#697 Refactor request & response, prepare for cakephp 4
  src/Controller/Admin/AdministrationBaseController.php
  src/Controller/AppController.php
  src/Controller/BulkController.php
  src/Controller/Component/HistoryComponent.php
  src/Controller/Component/ModulesComponent.php
  src/Controller/DashboardController.php
  src/Controller/DownloadController.php
  src/Controller/ExportController.php
  src/Controller/HistoryController.php
  src/Controller/ImportController.php
  src/Controller/LockController.php
  src/Controller/LoginController.php
  src/Controller/Model/CategoriesController.php
  src/Controller/Model/ExportController.php
  src/Controller/Model/ModelBaseController.php
  src/Controller/Model/PropertyTypesController.php
  src/Controller/ModulesController.php
  src/Controller/PasswordController.php
  src/Controller/TranslationsController.php
  src/Controller/TranslatorController.php
  src/Controller/TrashController.php
  src/Controller/UserProfileController.php
  src/View/AjaxView.php
  tests/TestCase/Controller/Admin/AdministrationBaseControllerTest.php
  tests/TestCase/Controller/AppControllerTest.php
  tests/TestCase/Controller/BulkControllerTest.php
  tests/TestCase/Controller/Component/FlashComponentTest.php
  tests/TestCase/Controller/Component/HistoryComponentTest.php
  tests/TestCase/Controller/Component/ModulesComponentTest.php
  tests/TestCase/Controller/Component/SchemaComponentTest.php
  tests/TestCase/Controller/DashboardControllerTest.php
  tests/TestCase/Controller/ExportControllerTest.php
  tests/TestCase/Controller/HistoryControllerTest.php
  tests/TestCase/Controller/ImportControllerTest.php
  tests/TestCase/Controller/LoginControllerTest.php
  tests/TestCase/Controller/Model/ModelBaseControllerTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
  tests/TestCase/Controller/TranslationsControllerTest.php
  tests/TestCase/Controller/TrashControllerTest.php
  tests/TestCase/Controller/UserProfileControllerTest.php
Labels: feature, Priority - Normal

#698 Decode json serialized fields
  src/Controller/AppController.php
  tests/TestCase/Controller/AppControllerTest.php
Labels: feature, Priority - High

#699 Tags admin page
  config/properties.php
  config/routes.php
  src/Controller/Model/TagsController.php
  src/Template/Element/Model/sidebar_links.twig
  src/Template/Element/Modules/index_tags.twig
  src/Template/Layout/js/app/app.js
  src/Template/Pages/Model/Tags/index.twig
  tests/TestCase/Controller/Model/TagsControllerTest.php
Labels: feature, Priority - High

#702 Update app.default.php, doc _hidden and _readonly relations config
  config/app.default.php
  src/Controller/Component/PropertiesComponent.php
  tests/TestCase/Controller/Component/PropertiesComponentTest.php
Labels: Priority - Normal, documentation
