Repository bedita/manager, pull requests merged in 2022-07, with the labels that each got.

#799 Admin Appearence
  config/app_local.example.php
  config/routes.php
  src/Controller/Admin/AppearenceController.php
  src/Controller/AppController.php
  src/Controller/Component/ConfigComponent.php
  src/Controller/Component/ModulesComponent.php
  src/Template/Element/Admin/sidebar.twig
  src/Template/Pages/Admin/Appearence/index.twig
  src/Template/Pages/Dashboard/index.twig
  src/View/Helper/LayoutHelper.php
  tests/TestCase/Controller/Admin/AppearenceControllerTest.php
  tests/TestCase/Controller/BulkControllerTest.php
  tests/TestCase/Controller/Component/CategoriesComponentTest.php
  tests/TestCase/Controller/Component/ConfigComponentTest.php
  tests/TestCase/Controller/Component/ModulesComponentTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
  tests/TestCase/Middleware/ProjectMiddlewareTest.php
Labels: feature, Priority - Normal, UI / UX

#806 Status endpoint
  src/Application.php
  src/Middleware/StatusMiddleware.php
  tests/TestCase/ApplicationTest.php
  tests/TestCase/Middleware/StatusMiddlewareTest.php
Labels: feature, Priority - Normal

#802 Validate uri on change
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Template/Layout/js/app/components/uri-input.js
Labels: feature, Priority - Normal, javascript

#807 Admin Appearence - Properties configuration
  src/Controller/Admin/AppearenceController.php
  src/Controller/Component/ConfigComponent.php
  src/Controller/Component/PropertiesComponent.php
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/pages/admin/appearence.js
  src/Template/Pages/Admin/Appearence/index.twig
  tests/TestCase/Controller/Admin/AppearenceControllerTest.php
  tests/TestCase/Controller/Component/PropertiesComponentTest.php
  tests/TestCase/Controller/Model/PropertyTypesControllerTest.php
Labels: feature, Priority - Normal

#808 Model relations view object types lists
  src/Controller/Model/RelationsController.php
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Template/Element/Model/relation_types.twig
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/object-types-list/object-types-list.js
  src/Template/Layout/js/app/pages/modules/view.js
  tests/TestCase/Controller/Model/RelationsControllerTest.php
Labels: feature, Priority - Normal, UI / UX, refactor

#801 chore: allow `id` as property value
  src/View/Helper/PropertyHelper.php
  tests/TestCase/View/Helper/PropertyHelperTest.php
Labels: feature

#810 Model -> modify object type: properties show/hide
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Template/Element/Model/object_property.twig
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/object-property/object-property.js
  src/Template/Layout/js/app/pages/modules/view.js
  src/Template/Pages/Model/ObjectTypes/view.twig
Labels: feature, Priority - Normal, UI / UX, javascript, refactor

#811 Refactor/translations view
  src/Template/Element/translation.twig
  src/Template/Pages/Translations/index.scss
  src/Template/Pages/Translations/index.twig
Labels: Priority - Normal, UI / UX

#809 Refactor/detail header and tab names
  src/Template/Element/Form/advanced_properties.twig
  src/Template/Element/Form/calendar.twig
  src/Template/Element/Form/categories.twig
  src/Template/Element/Form/core_properties.twig
  src/Template/Element/Form/history.twig
  src/Template/Element/Form/map.twig
  src/Template/Element/Form/media.twig
  src/Template/Element/Form/meta.twig
  src/Template/Element/Form/other_properties.twig
  src/Template/Element/Form/publish_properties.twig
  src/Template/Element/Form/related_translations.twig
  src/Template/Element/Form/relations.twig
  src/Template/Element/Form/roles.twig
  src/Template/Element/Form/tags.twig
  src/Template/Element/Form/trees.twig
  src/Template/Pages/Modules/_modules-view.scss
  src/Template/Pages/Modules/view.twig
Labels: Priority - Normal, UI / UX

#812 Model object type modify: delete property
  src/Template/Layout/js/app/components/object-property/object-property.js
Labels: feature, Priority - Normal

#814 Admin Appearence: AlertMessage and Project
  src/Controller/Admin/AppearenceController.php
  src/Controller/Component/ModulesComponent.php
  src/Template/Pages/Admin/Appearence/index.twig
  tests/TestCase/Controller/Admin/AppearenceControllerTest.php
  tests/TestCase/Controller/BulkControllerTest.php
  tests/TestCase/Controller/Component/ModulesComponentTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
Labels: feature, Priority - Normal

#815 Data Modeling -> Object types modify: parent_name and table as combo
  config/app_local.example.php
  src/Controller/Component/SchemaComponent.php
  src/Controller/Model/ObjectTypesController.php
  tests/TestCase/Controller/Component/SchemaComponentTest.php
  tests/TestCase/Controller/Model/ObjectTypesControllerTest.php
Labels: feature, Priority - Normal

#817 Admin Appearence: Export and Pagination
  src/Controller/Admin/AppearenceController.php
  src/Controller/Component/ModulesComponent.php
  src/Controller/ExportController.php
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Template/Layout/js/app/pages/admin/appearence.js
  src/Template/Pages/Admin/Appearence/index.twig
  tests/TestCase/Controller/Admin/AppearenceControllerTest.php
  tests/TestCase/Controller/BulkControllerTest.php
  tests/TestCase/Controller/ExportControllerTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
Labels: feature, Priority - Normal

#823 Fix `PermsHelper::canLock()`
  src/View/Helper/PermsHelper.php
  tests/TestCase/View/Helper/PermsHelperTest.php
Labels: bug

#821 Login password toggle show/hide
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/login-password/login-password.js
  src/Template/Pages/Login/login.twig
Labels: feature, Priority - Normal, UI / UX

#826 Admin Applications client_secret
  config/schema_properties.php
  src/Controller/Admin/ApplicationsController.php
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Template/Element/Admin/index_content.twig
  src/Template/Layout/js/app/components/secret/secret.js
  src/View/Helper/AdminHelper.php
  tests/TestCase/Controller/Admin/ApplicationsControllerTest.php
  tests/TestCase/View/Helper/AdminHelperTest.php
Labels: feature, Priority - Normal
