Repository bedita/manager, pull requests merged in 2022-05, with the labels that each got.

#759 Custom labels
  config/app.default.php
  src/Form/Control.php
  src/Form/Options.php
  src/View/Helper/PropertyHelper.php
  src/View/Helper/SchemaHelper.php
  tests/TestCase/Form/ControlTest.php
  tests/TestCase/View/Helper/PropertyHelperTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: feature, Priority - Normal, refactor

#763 Show history when manager user can access `users` module
  src/Template/Pages/Modules/view.twig
Labels: bug, Priority - Normal

#761 Fix filter-box in relation box of an object view: filters disappear when using more filters
  src/Template/Element/Form/relation.twig
  src/Template/Layout/js/app/components/filter-box.js
  src/Template/Layout/js/app/components/relation-view/relation-view.js
Labels: bug, Priority - Normal

#766 Filter by tags + fix categories and history_editor filters
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Locale/master.pot
  src/Template/Element/FilterBox/filter_box.scss
  src/Template/Element/FilterBox/filter_box_common.twig
  src/Template/Element/Form/tags.twig
  src/Template/Layout/js/app/components/category-picker/category-picker.js
  src/Template/Layout/js/app/components/filter-box.js
  src/Template/Layout/js/app/components/tag-picker/tag-picker.js
  src/Template/Layout/js/app/mixins/paginated-content.js
  src/Template/Layout/js/app/pages/modules/index.js
Labels: feature, Priority - High, javascript

#767 Javascript github action node 14.x and 16.x
  .github/workflows/javascript.yml
Labels: feature, Priority - Normal, javascript

#768 Github actions ubuntu-latest
  .github/workflows/javascript.yml
  .github/workflows/php.yml
Labels: feature, Priority - Normal

#769 Admin config page, content json field min-width 400
  src/Template/Element/Admin/index_content.twig
  src/Template/Pages/Admin/_admin.scss
Labels: bug, Priority - Normal, UI / UX

#770 Fix filter-box initFolder + save json field
  src/Controller/AppController.php
  src/Template/Layout/js/app/components/filter-box.js
Labels: bug, Priority - High

#765 phpstan level 5 + more coverage
  README.md
  composer.json
  phpstan.neon.dist
  src/Application.php
  src/Controller/AppController.php
  src/Controller/ModulesController.php
  src/Core/Exception/UploadException.php
  src/Middleware/ProjectMiddleware.php
  src/View/Helper/LinkHelper.php
  tests/TestCase/Controller/AppControllerTest.php
  tests/TestCase/Controller/Component/CategoriesComponentTest.php
  tests/TestCase/Controller/Component/FlashComponentTest.php
  tests/TestCase/Controller/Component/HistoryComponentTest.php
  tests/TestCase/Controller/Component/ModulesComponentTest.php
  tests/TestCase/Controller/Component/ObjectsEditorsComponentTest.php
  tests/TestCase/Controller/Component/ProjectConfigurationComponentTest.php
  tests/TestCase/Controller/Component/QueryComponentTest.php
  tests/TestCase/Controller/Component/SchemaComponentTest.php
  tests/TestCase/Controller/Component/ThumbsComponentTest.php
  tests/TestCase/Controller/Component/TranslatorComponentTest.php
  tests/TestCase/Controller/ImportControllerTest.php
  tests/TestCase/Controller/Model/CategoriesControllerTest.php
  tests/TestCase/Controller/Model/ExportControllerTest.php
  tests/TestCase/Controller/Model/ObjectTypesControllerTest.php
  tests/TestCase/Controller/Model/PropertyTypesControllerTest.php
  tests/TestCase/Controller/Model/RelationsControllerTest.php
  tests/TestCase/Controller/Model/TagsControllerTest.php
  tests/TestCase/Controller/TranslatorControllerTest.php
  tests/TestCase/Middleware/ProjectMiddlewareTest.php
  tests/TestCase/Utility/ApplicationsTest.php
  tests/TestCase/View/Helper/LinkHelperTest.php
Labels: feature, Priority - Normal, refactor

#774 Handle abstract types
  src/Controller/Component/SchemaComponent.php
  src/Template/Layout/js/app/components/relation-view/relations-add.js
  tests/TestCase/Controller/Component/SchemaComponentTest.php
Labels: bug, Priority - Normal

#772 Save object: add loader and handle malformed json response
  src/Template/Layout/js/app/pages/modules/view.js
Labels: feature, Priority - Normal, javascript

#764 View object history when users module not accessible (without created by / modified by)
  src/Template/Layout/js/app/components/history/history-info.js
  src/Template/Layout/js/app/components/history/history.js
  src/Template/Layout/js/app/components/property-view/property-view.js
  src/Template/Pages/Modules/view.twig
  src/View/Helper/LayoutHelper.php
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: feature, Priority - Normal

#776 Add form attribute to filter inputs
  src/Template/Element/FilterBox/filter_box_common.twig
  src/Template/Element/FilterBox/filter_box_page_toolbar.twig
  src/Template/Layout/js/app/components/category-picker/category-picker.js
  src/Template/Layout/js/app/components/folder-picker/folder-picker.js
  src/Template/Layout/js/app/components/input-dynamic-attributes.js
  src/Template/Layout/js/app/components/tag-picker/tag-picker.js
Labels: bug, Priority - High

#779 Split children updates
  src/Controller/Component/ModulesComponent.php
Labels: bug, Priority - High
