Repository bedita/manager, pull requests merged in 2022-04, with the labels that each got.

#746 Refactor webpack - alternate paths for locales, templates and javascript root
  webpack.config.environment.js
  webpack.config.js
  webpack.config.plugin.js
Labels: bug, Priority - High, javascript, refactor

#749 Twig fix load custom elements
  src/Template/Element/Form/other_properties.twig
Labels: bug, Priority - High, refactor

#750 Dialog functions in BEDITA object (for plugins usage)
  src/Template/Layout/js/app/app.js
Labels: feature, Priority - High, javascript

#752 Trash link only for object types
  src/Template/Element/Menu/menu.twig
  src/View/Helper/LayoutHelper.php
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: bug, Priority - Normal

#728 Load optional plugin DebugKit
  src/Application.php
Labels: bug, feature, Priority - Normal

#754 Bump moment to 2.29.2
  package.json
  yarn.lock
Labels: feature, Priority - High, dependencies

#755 fix: Check if response exists before calling hash function
  src/Controller/Component/ThumbsComponent.php
Labels: bug, Priority - Normal

#756 Upgrade js dependencies
  yarn.lock
Labels: Priority - Normal, dependencies, javascript

#757 BEdita 4.7.0
  .github/workflows/php.yml
  README.md
  tests/TestCase/Authentication/Identifier/Resolver/ApiResolverTest.php
  tests/TestCase/Controller/Admin/AdministrationBaseControllerTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
Labels: feature, Priority - Normal

#760 Applications api keys
  src/Controller/Admin/AdministrationBaseController.php
  src/Controller/Admin/ApplicationsController.php
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Locale/master.pot
  src/Template/Element/Admin/index_content.twig
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/secret/secret.js
  src/Template/Layout/js/app/pages/admin/index.js
  tests/TestCase/Controller/Admin/ApplicationsControllerTest.php
Labels: feature, Priority - Normal
