Repository bedita/manager, pull requests merged in 2022-06, with the labels that each got.

#781 Export related objects
  config/routes.php
  src/Controller/ExportController.php
  src/Template/Element/Form/relation.twig
  src/Template/Layout/js/app/components/relation-view/relation-view.js
  tests/TestCase/Controller/ExportControllerTest.php
Labels: feature, Priority - Normal

#777 Endpoints + EndpointPermissions
  .github/workflows/php.yml
  README.md
  config/routes.php
  src/Controller/Admin/ApplicationsController.php
  src/Controller/Admin/AsyncJobsController.php
  src/Controller/Admin/ConfigController.php
  src/Controller/Admin/EndpointPermissionsController.php
  src/Controller/Admin/EndpointsController.php
  src/Controller/Admin/RolesController.php
  src/Template/Element/Admin/index_content.twig
  src/Template/Element/Admin/sidebar.twig
  src/Template/Pages/Admin/EndpointPermissions/index.twig
  src/View/Helper/AdminHelper.php
  src/View/Helper/LayoutHelper.php
  tests/TestCase/Controller/Admin/EndpointPermissionsControllerTest.php
  tests/TestCase/View/Helper/LinkHelperTest.php
Labels: feature, Priority - Normal

#780 Clone object with relations
  src/Controller/Component/CloneComponent.php
  src/Controller/Component/ModulesComponent.php
  src/Controller/ModulesController.php
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Locale/master.pot
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/dialog/dialog.js
  src/Template/Layout/js/app/components/dialog/dialog.scss
  tests/TestCase/Controller/Component/CloneComponentTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
Labels: feature, Priority - Normal

#783 Enhance Date Ranges, adding "Every day" and weekdays
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Locale/master.pot
  src/Template/Element/Form/calendar.scss
  src/Template/Element/Form/calendar.twig
  src/Template/Layout/js/app/components/date-ranges-view/date-ranges-view.js
Labels: feature, Priority - Normal, javascript, refactor

#782 Refactor categories
  config/routes.php
  src/Controller/CategoriesController.php
  src/Controller/Component/CategoriesComponent.php
  src/Controller/Model/CategoriesController.php
  src/Controller/ModulesController.php
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Locale/master.pot
  src/Template/Element/Modules/index_categories.twig
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/category/category.js
  src/Template/Pages/Categories/index.twig
  src/Template/Pages/Model/Categories/index.twig
  tests/TestCase/Controller/CategoriesControllerTest.php
  tests/TestCase/Controller/Component/CategoriesComponentTest.php
  tests/TestCase/Controller/Model/CategoriesControllerTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
Labels: feature, Priority - Normal, refactor

#785 Fix Control::categories notice
  src/Form/Control.php
Labels: bug, Priority - Normal

#790 Upgrade js dependencies
  yarn.lock
Labels: Priority - Normal, dependencies, javascript

#789 Cakephp 4.4.0
  README.md
  composer.json
  config/.env.example
  config/app.default.php
  config/bootstrap.php
  config/bootstrap_cli.php
  config/paths.php
  src/Application.php
  src/Console/Installer.php
  src/Controller/CategoriesController.php
  tests/.env.example
  tests/TestCase/Command/ConsoleCommandTest.php
  tests/TestCase/Controller/Component/HistoryComponentTest.php
  tests/TestCase/View/Helper/AdminHelperTest.php
  tests/TestCase/View/Helper/CategoriesHelperTest.php
  tests/TestCase/View/Helper/PropertyHelperTest.php
Labels: feature, Priority - High, dependencies

#788 i18n 4.1
  composer.json
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
Labels: feature, Priority - Normal, dependencies

#762 Add `view/download` on related stream
  src/Template/Element/Form/related_item.twig
  src/Template/Layout/js/app/components/relation-view/relation-view.js
Labels: feature, Priority - Normal, UI / UX

#793 Fix console js errors in new object creation page
  src/Template/Element/Form/relation.twig
  src/Template/Element/Form/tags.twig
  src/Template/Element/Panel/relations_add.twig
Labels: bug, Priority - Normal, javascript

#794 Avoid API client creation in component initialize
  src/Controller/Component/CloneComponent.php
  tests/TestCase/Controller/Component/CloneComponentTest.php
Labels: bug

#797 Input uri and email
  src/Form/Control.php
  src/Form/Form.php
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/email-input.js
  src/Template/Layout/js/app/components/uri-input.js
  src/Template/Layout/js/app/directives/email.js
  src/Template/Layout/js/app/directives/uri.js
  tests/TestCase/Form/ControlTest.php
  tests/TestCase/Form/FormTest.php
Labels: feature, Priority - Normal, UI / UX

#796 Clone relations - 100 related
  src/Controller/Component/CloneComponent.php
Labels: feature, Priority - Normal

#748 Introduce `app_local.php` conf
  .gitignore
  README.md
  composer.json
  config/.env.example
  config/app.default.php
  config/app.php
  config/app_local.example.php
  config/bootstrap.php
  src/Application.php
  src/Command/ConsoleCommand.php
  src/Console/Installer.php
  src/Plugin.php
  tests/TestCase/Command/ConsoleCommandTest.php
Labels: refactor

#798 Svelte json editor
  package.json
  src/Template/Layout/js/app/components/json-editor-input.js
  src/Template/Layout/styles/_forms.scss
  yarn.lock
Labels: feature, Priority - Normal, UI / UX, javascript

#784 Tabs background
  src/Template/Element/Form/advanced_properties.twig
  src/Template/Element/Form/calendar.twig
  src/Template/Element/Form/categories.twig
  src/Template/Element/Form/history.twig
  src/Template/Element/Form/map.twig
  src/Template/Element/Form/media.twig
  src/Template/Element/Form/meta.twig
  src/Template/Element/Form/other_properties.twig
  src/Template/Element/Form/related_translations.twig
  src/Template/Element/Form/relations.twig
  src/Template/Element/Form/roles.twig
  src/Template/Element/Form/tags.twig
  src/Template/Element/Form/trees.twig
  src/Template/Pages/Modules/_modules-view.scss
Labels: feature, Priority - Normal, UI / UX
