Repository bedita/manager, pull requests merged in 2022-09, with the labels that each got.

#833 Release workflow
  .github/workflows/release.yml
  config/version.ini
Labels: release:patch

#834 Debug release workflow
  .github/workflows/release.yml
Labels: release:patch

#835 Debug release workflow
  .github/workflows/release.yml
Labels: release:patch

#836 Remove release workflow
  .github/workflows/release.yml
Labels: refactor

#830 Date range validation
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Template/Element/Form/form.scss
  src/Template/Layout/js/app/components/date-input.js
  src/Template/Layout/js/app/components/date-ranges-view/date-ranges-view.js
Labels: feature, Priority - Normal, javascript

#838 Github action release workflow
  .github/workflows/release.yml
Labels: release:patch

#832 Enhance filter UI
  src/Template/Element/FilterBox/filter_box.scss
  src/Template/Element/FilterBox/filter_box_common.twig
Labels: feature, Priority - Normal, UI / UX, release:patch

#837 Add ancestor to allowed filters list
  src/Template/Layout/js/app/components/filter-box.js
Labels: bug, release:patch

#839 Introduce BEdita v5 in CI
  .github/workflows/php.yml
  tests/TestCase/Controller/Component/ModulesComponentTest.php
Labels: release:patch

#841 Reintroduce translation styles - fix translation view UI
  src/Template/Layout/style.scss
  src/Template/Pages/Translations/index.scss
Labels: Priority - Normal, release:patch

#843 Fix BEdita5 integration with API configuration and limit config keys
  src/Controller/Admin/AppearenceController.php
  src/Utility/ApiConfigTrait.php
  tests/TestCase/Utility/ApiConfigTraitTest.php
Labels: bug, release:patch

#847 Default lang for combo language in object view
  src/Form/Options.php
  src/Template/Element/Form/related_translations.twig
  src/Utility/ApiConfigTrait.php
  tests/TestCase/Form/OptionsTest.php
  tests/TestCase/Utility/ApiConfigTraitTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: bug, Priority - High, release:patch

#849 Selected types filter in trash
  src/Template/Element/filter_type.twig
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/components/filter-type.js
Labels: bug, Priority - Normal, release:patch

#844 Roles Modules accesses admin page
  config/routes.php
  src/Controller/Admin/RolesModulesController.php
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Template/Element/Admin/sidebar.twig
  src/Template/Layout/js/app/pages/admin/index.js
  src/Template/Pages/Admin/RolesModules/index.twig
  src/Template/Pages/Admin/_admin.scss
  src/Utility/ApiConfigTrait.php
  src/View/Helper/LayoutHelper.php
  src/View/Helper/PermsHelper.php
  tests/TestCase/Controller/Admin/RolesModulesControllerTest.php
  tests/TestCase/Utility/ApiConfigTraitTest.php
  tests/TestCase/View/Helper/PermsHelperTest.php
Labels: feature, Priority - Normal, release:patch

#851 Fix property bulk action label
  src/Template/Element/Form/bulk_properties.twig
Labels: UI / UX, release:patch
