Repository bedita/manager, pull requests merged in 2022-10, with the labels that each got.

#854 Disable editing for referenced locations
  src/Template/Element/Form/form.scss
  src/Template/Layout/js/app/components/locations-view/location-view.js
Labels: feature, UI / UX, release:patch

#855 Avoid unwanted `format-{relation}` items in form data
  src/Template/Element/Form/relation.twig
Labels: bug, release:patch

#852 Fast create form: fields types
  src/Controller/ModulesController.php
  src/Template/Element/Panel/relations_add.twig
  src/Template/Layout/js/app/components/relation-view/relations-add.js
  src/View/Helper/PropertyHelper.php
  tests/TestCase/Controller/ModulesControllerTest.php
  tests/TestCase/View/Helper/PropertyHelperTest.php
Labels: bug, feature, Priority - High, UI / UX, release:patch

#853 Introduce custom bulk actions
  config/routes.php
  src/Controller/BulkController.php
  src/Core/Bulk/CustomBulkActionInterface.php
  src/Template/Element/Form/bulk_custom.twig
  src/Template/Element/Form/bulk_properties.twig
  src/Template/Element/Modules/index_bulk.twig
  tests/TestCase/Controller/BulkControllerTest.php
  tests/TestCase/Controller/CustomBulkAction.php
Labels: feature, release:minor

#857 bootstrap_cli: fix for command line exceptions and bake usage
  config/bootstrap_cli.php
Labels: bug, Priority - Normal, release:patch

#859 Remove location suffix from autocomplete
  src/Template/Layout/js/app/components/locations-view/location-view.js
Labels: bug, UI / UX, release:patch

#858 Add custom sidebar links via `modules` conf
  config/app.php
  config/app_local.example.php
  src/Template/Pages/Modules/index.twig
  src/Template/Pages/Modules/view.twig
Labels: feature, Priority - Normal, UI / UX, release:patch

#861 Fix CSRF cookie error on login
  config/bootstrap.php
Labels: bug, release:patch

#862 chore: remove getFullLabel
  src/Template/Layout/js/app/components/tag-picker/tag-picker.js
Labels: javascript, release:patch

#863 Fix substitute appearence with appearance
  config/routes.php
  src/Controller/Admin/AppearanceController.php
  src/Locale/default.pot
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Template/Element/Admin/sidebar.twig
  src/Template/Layout/js/app/app.js
  src/Template/Layout/js/app/pages/admin/appearance.js
  src/Template/Pages/Admin/Appearance/index.twig
  src/Template/Pages/Dashboard/index.twig
  src/View/Helper/LayoutHelper.php
  tests/TestCase/Controller/Admin/AppearanceControllerTest.php
Labels: Priority - Low, refactor, release:patch

#864 Fix save action on Model/Property Types
  src/Application.php
  src/Controller/Model/PropertyTypesController.php
  src/Template/Layout/js/app/pages/model/index.js
Labels: bug, release:patch

#867 Fix bugs found by scrutinizer
  src/Console/Installer.php
  src/Form/Control.php
  src/View/Helper/ArrayHelper.php
  src/View/Helper/LinkHelper.php
Labels: bug, Priority - Normal, release:patch

#874 Include users when fetching history
  src/Controller/Component/HistoryComponent.php
  src/Template/Layout/js/app/components/history/history.js
  tests/TestCase/Controller/Component/HistoryComponentTest.php
Labels: feature, Priority - Normal, release:patch
