Repository bedita/manager, pull requests merged in 2022-12, with the labels that each got.

#898 Fix PermsHelper possible RuntimeError
  src/View/Helper/PermsHelper.php
Labels: bug, Priority - High, release:patch

#903 Vulnerability fix: bump tinymce from 5.10.5 to 5.10.7
  package.json
  yarn.lock
Labels: Priority - Normal, dependencies, javascript

#900 Folders children order
  .github/workflows/php.yml
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/relation-view/relation-view.js
  resources/js/app/mixins/paginated-content.js
  src/Controller/Component/PropertiesComponent.php
  src/Form/Options.php
  templates/Element/Form/related_item.twig
  templates/Element/Form/relation.twig
  templates/Element/Form/relations.twig
  templates/Pages/Modules/view.twig
  tests/TestCase/Controller/Model/PropertyTypesControllerTest.php
  tests/TestCase/Form/OptionsTest.php
Labels: feature, Priority - High, release:minor

#904 Browsers data updating for browserslist
  yarn.lock
Labels: dependencies, javascript

#901 Fix translations module types filter
  src/Controller/TranslationsController.php
  tests/TestCase/Controller/TranslationsControllerTest.php
Labels: bug, release:patch

#906 Retrocompatibility fix: folders.children_order
  templates/Element/Form/related_item.twig
  templates/Element/Form/relation.twig
Labels: bug, Priority - High, release:patch

#883 BEdita API version check
  config/bedita-api-version.ini
  config/bootstrap.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  src/View/Helper/SystemHelper.php
  templates/Element/Menu/colophon.scss
  templates/Element/Menu/colophon.twig
  templates/Layout/default.twig
  tests/TestCase/View/Helper/SystemHelperTest.php
Labels: feature, Priority - Normal, release:patch

#902 Enable translations export
  resources/js/app/pages/modules/index.js
  resources/style.scss
  templates/Element/Form/bulk_export.twig
  templates/Pages/Translations/index.scss
  templates/Pages/Translations/index.twig
  templates/Pages/Translations/view.scss
Labels: feature, release:patch

#908 Clear schema on model change
  src/Controller/Component/SchemaComponent.php
  src/Controller/Model/ModelBaseController.php
  src/Controller/Model/PropertyTypesController.php
Labels: feature

#907 Hide disabled categories, set enabled as default in creation
  resources/js/app/components/category/category.js
  src/Controller/Component/SchemaComponent.php
  src/Form/Control.php
  src/View/Helper/CategoriesHelper.php
  tests/TestCase/Controller/Component/HistoryComponentTest.php
  tests/TestCase/Controller/Component/SchemaComponentTest.php
  tests/TestCase/Form/ControlTest.php
  tests/TestCase/View/Helper/CategoriesHelperTest.php
  tests/TestCase/View/Helper/PropertyHelperTest.php
Labels: bug, release:patch

#909 Add richtext editor typos plugin
  package.json
  resources/js/app/directives/richeditor.js
  yarn.lock
Labels: feature, javascript, release:patch

#910 Admin module minor styling
  templates/Element/Admin/index_content.twig
  templates/Element/Admin/sidebar.twig
  templates/Layout/default.twig
  templates/Pages/Admin/_admin.scss
  templates/Pages/UserProfile/view.twig
  webpack.config.js
  webroot/favicon.png
Labels: UI / UX, release:patch

#911 Avoid error when saving a relation with `params`
  src/Controller/Model/RelationsController.php
Labels: bug, release:patch
