Repository bedita/manager, pull requests merged in 2022-03, with the labels that each got.

#720 Refactor: phpcs
  src/Controller/BulkController.php
  src/Controller/LoginController.php
  src/Middleware/ProjectMiddleware.php
  tests/TestCase/Authentication/Identifier/ApiIdentifierTest.php
  tests/TestCase/Authentication/Identifier/Resolver/ApiResolverTest.php
  tests/TestCase/Controller/DashboardControllerTest.php
  tests/TestCase/Controller/Model/ModelBaseControllerTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
Labels: Priority - High, refactor

#722 Csrf token in meta config
  src/View/Helper/LayoutHelper.php
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: bug, Priority - High

#724 Load bootstrap CLI
  src/Application.php
  tests/TestCase/ApplicationTest.php
Labels: bug

#727 Fix file import
  phpunit.xml.dist
  src/Controller/ImportController.php
  tests/TestCase/Controller/ImportControllerTest.php
Labels: bug, Priority - High

#730 Upload in ModulesComponent
  src/Controller/Component/ModulesComponent.php
  tests/TestCase/Controller/Component/ModulesComponentTest.php
Labels: bug, Priority - High

#732 Check file size on upload
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Locale/master.pot
  src/Template/Element/Form/media.twig
  src/Template/Element/Form/upload.twig
  src/Template/Layout/js/app/components/form-file-upload.js
  src/Template/Layout/js/app/pages/import/index.js
  src/Template/Pages/Import/index.twig
  src/View/AppView.php
  src/View/Helper/LayoutHelper.php
  src/View/Helper/SystemHelper.php
  tests/TestCase/View/Helper/LayoutHelperTest.php
  tests/TestCase/View/Helper/SystemHelperTest.php
Labels: bug, Priority - Normal

#734 Check file size on drag and drop
  src/Locale/en_US/default.po
  src/Locale/it_IT/default.po
  src/Locale/master.pot
  src/Template/Layout/js/app/components/drop-upload.js
  src/Template/Layout/js/app/components/form-file-upload.js
  src/Template/Layout/js/app/helpers/download.js
  src/Template/Layout/js/app/helpers/view.js
  src/Template/Layout/js/app/pages/import/index.js
Labels: feature, Priority - Normal

#737 Replace more aliased classes
  .github/workflows/php.yml
  composer.json
  src/Command/ConsoleCommand.php
  src/Core/Exception/UploadException.php
Labels: bug, Priority - High

#739 Bump minimist to 1.2.6
  yarn.lock
Labels: Priority - High, dependencies, javascript

#740 Correctly handle boolean relation param
  src/Template/Layout/js/app/components/edit-relation-param.js
Labels: bug, Priority - Normal, javascript

#741 Update phpstan/phpstan to version 1.5 + fix php workflow
  .github/workflows/php.yml
  .gitignore
  composer.json
  phpstan.neon.dist
  tests/TestCase/Controller/BulkControllerTest.php
  tests/TestCase/Controller/Component/CategoriesComponentTest.php
  tests/TestCase/Controller/Component/ModulesComponentTest.php
  tests/TestCase/Controller/Component/ObjectsEditorsComponentTest.php
  tests/TestCase/Controller/Component/ThumbsComponentTest.php
  tests/TestCase/Controller/ExportControllerTest.php
  tests/TestCase/Controller/Model/CategoriesControllerTest.php
  tests/TestCase/Controller/Model/ExportControllerTest.php
  tests/TestCase/Controller/Model/ObjectTypesControllerTest.php
  tests/TestCase/Controller/Model/PropertyTypesControllerTest.php
  tests/TestCase/Controller/Model/TagsControllerTest.php
  tests/TestCase/Form/FormTest.php
  tests/TestCase/View/Helper/AdminHelperTest.php
  tests/Utils/ModulesControllerSample.php
Labels: feature, Priority - Normal

#743 Update README
  README.md
Labels: Priority - Normal, documentation

#742 phpstan level 2
  .github/workflows/php.yml
  phpstan.neon.dist
  src/Controller/Admin/AdministrationBaseController.php
  src/Controller/AppController.php
  src/Controller/Component/CategoriesComponent.php
  src/Controller/Component/ModulesComponent.php
  src/Controller/Component/ObjectsEditorsComponent.php
  src/Controller/Component/ThumbsComponent.php
  src/Controller/Component/TranslatorComponent.php
  src/Controller/ErrorController.php
  src/Controller/Model/ModelBaseController.php
  src/Controller/Model/PropertyTypesController.php
  src/Controller/ModulesController.php
  src/Controller/PasswordController.php
  src/Controller/TranslationsController.php
  src/Controller/TrashController.php
  src/Core/Filter/ImportFilter.php
  src/Core/Result/ImportResult.php
  src/Middleware/ProjectMiddleware.php
  src/View/Helper/LayoutHelper.php
  src/View/Helper/SchemaHelper.php
  tests/TestCase/ApplicationTest.php
  tests/TestCase/Controller/Admin/ApplicationsControllerTest.php
  tests/TestCase/Controller/Admin/AsyncJobsControllerTest.php
  tests/TestCase/Controller/Admin/EndpointsControllerTest.php
  tests/TestCase/Controller/Admin/RolesControllerTest.php
  tests/TestCase/Controller/AppControllerTest.php
  tests/TestCase/Controller/BulkControllerTest.php
  tests/TestCase/Controller/Component/FlashComponentTest.php
  tests/TestCase/Controller/Component/ModulesComponentTest.php
  tests/TestCase/Controller/Component/ObjectsEditorsComponentTest.php
  tests/TestCase/Controller/Component/PropertiesComponentTest.php
  tests/TestCase/Controller/Component/QueryComponentTest.php
  tests/TestCase/Controller/Component/ThumbsComponentTest.php
  tests/TestCase/Controller/DashboardControllerTest.php
  tests/TestCase/Controller/ExportControllerTest.php
  tests/TestCase/Controller/HistoryControllerTest.php
  tests/TestCase/Controller/ImportControllerTest.php
  tests/TestCase/Controller/LoginControllerTest.php
  tests/TestCase/Controller/Model/ObjectTypesControllerTest.php
  tests/TestCase/Controller/Model/PropertyTypesControllerTest.php
  tests/TestCase/Controller/Model/RelationsControllerTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
  tests/TestCase/Controller/PasswordControllerTest.php
  tests/TestCase/Controller/TranslationsControllerTest.php
  tests/TestCase/Controller/TranslatorControllerTest.php
  tests/TestCase/Controller/TrashControllerTest.php
  tests/TestCase/Controller/UserProfileControllerTest.php
  tests/TestCase/Middleware/ProjectMiddlewareTest.php
  tests/TestCase/Utility/TranslateTest.php
  tests/TestCase/View/Helper/LinkHelperTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
  tests/Utils/DummyImportFilter.php
  tests/Utils/ModulesControllerSample.php
Labels: feature, Priority - Normal, refactor

#744 Refactor: more coverage
  src/Auth/ApiAuthenticate.php
  src/Command/ConsoleCommand.php
  tests/TestCase/Command/ConsoleCommandTest.php
Labels: feature, Priority - Normal, refactor
