Repository bedita/manager, pull requests merged in 2023-10, with the labels that each got.

#1049 Improve oembed feature
  config/oembed.php
  src/Utility/OEmbed.php
  templates/Element/Form/media.twig
  tests/TestCase/Utility/OEmbedTest.php
Labels: feature, Priority - High, release:minor

#1051 Admin pages minor style fixes
  resources/js/app/components/relation-view/roles-list-view.vue
  templates/Pages/Admin/RolesModules/index.twig
  webroot/css/objects-history.css
Labels: Priority - Normal, UI / UX, refactor, release:patch

#1045 Fix eslintrc rules
  .eslintrc.js
  .github/workflows/javascript.yml
  resources/js/app/components/json-editor/json-editor.vue
  resources/js/app/components/object-property/object-properties.vue
  resources/js/app/components/object-property/object-property.vue
  resources/js/app/components/objects-history/objects-history.vue
  resources/js/app/components/relation-view/roles-list-view.vue
  resources/js/app/components/tag-picker/tag-picker.vue
  resources/js/app/components/thumbnail/thumbnail.vue
  resources/js/app/components/user-accesses/user-accesses.vue
Labels: javascript, refactor
