Repository bedita/manager, pull requests merged in 2023-12, with the labels that each got.

#1067 Update typos library
  yarn.lock
Labels: bug, Priority - Normal, dependencies, javascript, release:patch

#1068 Refactor/minor styles
  templates/Element/custom_colors.twig
Labels: UI / UX, refactor, release:patch

#1065 `AlertMessageByArea` configuration
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  src/Utility/ApiConfigTrait.php
  src/View/Helper/SystemHelper.php
  templates/Element/custom_colors.twig
  templates/Layout/default.twig
  templates/Pages/Admin/Appearance/index.twig
  tests/TestCase/View/Helper/SystemHelperTest.php
Labels: feature, UI / UX, release:patch

#1069 Upgrade javascript dependencies
  yarn.lock
Labels: dependencies, javascript

#1070 User's Dashboard Recent Activity
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/app.js
  resources/js/app/components/recent-activity/recent-activity.vue
  resources/js/app/pages/dashboard/index.js
  resources/js/app/plugins/tinymce/placeholders.js
  src/Controller/DashboardController.php
  templates/Pages/Dashboard/_dashboard.scss
  templates/Pages/Dashboard/index.twig
  tests/TestCase/Controller/DashboardControllerTest.php
Labels: feature, release:minor

#1071 Fix loader and error in Recent Activity
  resources/js/app/components/recent-activity/recent-activity.vue
Labels: bug, Priority - High, UI / UX, release:patch

#1074 Bump cakephp-codesniffer from v4.5.1 to v4.7.0
  composer.json
  src/Controller/Component/HistoryComponent.php
Labels: dependencies, integration

#1072 Cakephp 4.5
  composer.json
  src/View/AppView.php
  tests/TestCase/Controller/Component/HistoryComponentTest.php
  tests/TestCase/View/Helper/AdminHelperTest.php
  tests/TestCase/View/Helper/CategoriesHelperTest.php
  tests/TestCase/View/Helper/LinkHelperTest.php
  tests/TestCase/View/Helper/PropertyHelperTest.php
Labels: dependencies, integration

#1073 Psalm check in github action CI
  .github/workflows/php.yml
  README.md
  composer.json
  psalm.xml
  src/Controller/Admin/EndpointPermissionsController.php
  src/Controller/AppController.php
  src/Controller/Component/CategoriesComponent.php
  src/Controller/Component/ExportComponent.php
  src/Controller/Component/HistoryComponent.php
  src/Controller/Component/ModulesComponent.php
  src/Controller/Component/QueryComponent.php
  src/Controller/Component/ThumbsComponent.php
  src/Controller/Model/PropertyTypesController.php
  src/Controller/Model/TagsController.php
  src/Controller/ModulesController.php
  src/Controller/TranslationsController.php
  src/Core/Filter/ImportFilter.php
  src/Plugin.php
  src/Utility/ApiConfigTrait.php
  src/Utility/Applications.php
  src/Utility/PermissionsTrait.php
  src/View/Helper/LayoutHelper.php
  src/View/Helper/PermsHelper.php
  src/View/Helper/PropertyHelper.php
  src/View/Helper/SchemaHelper.php
Labels: refactor, integration
