Repository bedita/manager, pull requests merged in 2023-06, with the labels that each got.

#1005 Render `text/html` fields as `input text` in filter search
  resources/js/app/components/input-dynamic-attributes.vue
  templates/Element/FilterBox/filter_box_common.twig
Labels: feature, UI / UX, refactor, release:patch

#1004 Refactor: save folder parent and children
  .github/workflows/javascript.yml
  resources/js/app/components/tree-view/tree-view.vue
  src/Controller/AppController.php
  src/Controller/Component/ChildrenComponent.php
  src/Controller/Component/ModulesComponent.php
  src/Controller/Component/ParentsComponent.php
  src/Controller/ModulesController.php
  src/Utility/ApiClientTrait.php
  templates/Element/Form/trees.twig
  tests/TestCase/Controller/AppControllerTest.php
  tests/TestCase/Controller/BaseControllerTest.php
  tests/TestCase/Controller/Component/ChildrenComponentTest.php
  tests/TestCase/Controller/Component/ModulesComponentTest.php
  tests/TestCase/Controller/Component/ParentsComponentTest.php
  tests/TestCase/Utility/ApiClientTraitTest.php
Labels: feature, Priority - High, refactor, release:patch

#987 Handle priority input
  config/bedita-api-version.ini
  resources/js/app/components/relation-view/relation-view.js
  templates/Element/Form/form.scss
  templates/Element/Form/related_item.twig
  templates/Element/Form/relations.scss
  tests/TestCase/View/Helper/SystemHelperTest.php
Labels: feature, Priority - High, release:minor

#1009 Custom template in view, without properties + build includes plugins install
  package.json
  resources/js/app/components/relation-view/relation-view.js
  templates/Element/Form/other_properties.twig
  yarn.lock
Labels: feature, Priority - High, javascript, release:patch, integration

#1012 Perms and locked by parents checks when folders do not have Permissions association
  src/View/Helper/PermsHelper.php
  tests/TestCase/View/Helper/PermsHelperTest.php
Labels: bug, Priority - High, release:patch

#1013 Fix sort in index pages
  src/Controller/Component/QueryComponent.php
  tests/TestCase/Controller/Component/QueryComponentTest.php
Labels: bug, release:patch

#1008 Nullable boolean properties shown as `select` in forms
  src/Form/Control.php
  src/Form/ControlType.php
  tests/TestCase/Form/ControlTest.php
  tests/TestCase/Form/ControlTypeTest.php
Labels: feature, UI / UX, release:patch

#1014 Fix saveRelatedObjects type, might be null
  src/Controller/Component/ModulesComponent.php
Labels: bug, Priority - High, release:patch

#1016 Fix a message typo
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  src/Controller/Component/ThumbsComponent.php
Labels: feature
