Repository bedita/manager, pull requests merged in 2023-02, with the labels that each got.

#926 Category name and tag name as slug
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/category/category.js
  resources/js/app/components/tag-form/tag-form.js
  resources/js/app/helpers/view.js
  templates/Element/Modules/index_tags.twig
  templates/Pages/Model/Tags/index.twig
Labels: feature, Priority - Normal, release:patch

#932 Mime types for audio, file and video
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/form-file-upload.js
  resources/js/app/components/property-view/property-view.js
  resources/js/app/helpers/view.js
  src/View/Helper/LayoutHelper.php
  src/View/Helper/SystemHelper.php
  templates/Element/Form/form_file_upload.twig
  tests/TestCase/View/Helper/LayoutHelperTest.php
  tests/TestCase/View/Helper/SystemHelperTest.php
Labels: feature, Priority - Normal, release:patch

#935 Update Axios to 1.2.6
  package.json
  yarn.lock
Labels: dependencies, javascript

#936 Fix i18n string in index header
  templates/Element/Modules/index_header.twig
  templates/Pages/Categories/index.twig
Labels: bug, UI / UX

#937 Fix module Links UI by refactoring modules classes
  templates/Element/Admin/sidebar.twig
  templates/Element/Menu/sidebar.scss
  templates/Element/Menu/sidebar.twig
  templates/Element/Model/sidebar_links.twig
  templates/Element/translation.twig
  templates/Pages/Admin/_admin.scss
  templates/Pages/Categories/index.twig
  templates/Pages/Import/index.twig
  templates/Pages/Login/login.twig
  templates/Pages/Model/ObjectTypes/view.twig
  templates/Pages/Model/Relations/view.twig
  templates/Pages/Modules/index.twig
  templates/Pages/Modules/view.twig
  templates/Pages/Password/reset.twig
  templates/Pages/Trash/index.twig
  templates/Pages/Trash/view.twig
  templates/Pages/UserProfile/view.twig
Labels: bug, UI / UX, refactor, release:patch

#939 Trash module index orderable columns
  src/Controller/TrashController.php
  src/View/Helper/LayoutHelper.php
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: feature, release:patch

#941 Refactor webpack + upgrade dependencies
  package.json
  resources/js/app/components/property-view/property-view.js
  resources/js/app/components/relation-view/relations-add.js
  resources/js/app/components/uri-input.js
  webpack.config.js
  yarn.lock
Labels: dependencies, javascript

#946 Customize options fields in forms
  resources/js/app/components/json-editor-input.js
  resources/js/app/directives/richeditor.js
  src/Form/Control.php
  src/View/Helper/PropertyHelper.php
  src/View/Helper/SchemaHelper.php
  templates/Element/Modules/index_table_header.twig
  tests/TestCase/Form/ControlTest.php
  tests/TestCase/View/Helper/PropertyHelperTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: feature, release:minor

#947 Min length 3 for category/tag name and label
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/category/category.js
  resources/js/app/components/tag-form/tag-form.js
  resources/js/app/components/tag-picker/tag-picker.js
  resources/js/app/helpers/view.js
Labels: feature, javascript, release:patch

#948 Fix control options for `Properties.<type>.options`
  resources/js/app/components/json-editor-input.js
  src/Form/Control.php
  src/View/Helper/PropertyHelper.php
  src/View/Helper/SchemaHelper.php
  tests/TestCase/View/Helper/PropertyHelperTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: bug, release:patch

#950 Improve thumbs component
  config/app_local.example.php
  config/bedita-api-version.ini
  src/Controller/Component/ThumbsComponent.php
  src/Controller/ModulesController.php
  templates/Element/Form/media.twig
  tests/TestCase/Controller/Component/ThumbsComponentTest.php
  tests/TestCase/View/Helper/LinkHelperTest.php
  tests/TestCase/View/Helper/SystemHelperTest.php
Labels: feature, release:patch

#952 Fix error template path
  resources/style.scss
  src/Controller/ErrorController.php
  templates/Error/_error.scss
  templates/Error/error400.twig
  templates/Error/error500.twig
  templates/Layout/error.twig
Labels: bug, UI / UX, release:patch

#954 Fix test for "translatable"
  tests/TestCase/Controller/Component/SchemaComponentTest.php
Labels: integration

#951 Custom control options configuration and interface
  resources/js/app/app.js
  resources/js/app/components/json-fields/key-value-list.js
  resources/js/app/components/json-fields/string-list.js
  resources/js/app/components/property-view/property-view.js
  resources/js/app/helpers/text-helper.js
  resources/js/libs/filters.js
  src/Controller/AppController.php
  src/Controller/Component/PropertiesComponent.php
  src/Form/CustomComponentControl.php
  src/Form/CustomHandlerInterface.php
  src/View/Helper/PropertyHelper.php
  src/View/Helper/SchemaHelper.php
  tests/TestCase/Controller/Component/PropertiesComponentTest.php
  tests/TestCase/Form/CustomComponentControlTest.php
  tests/TestCase/View/Helper/PropertyHelperTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: feature, release:minor

#953 PHP 8.2 support
  .github/workflows/php.yml
  README.md
Labels: integration

#956 Handle empty schema as 'json'
  src/Form/ControlType.php
  src/View/Helper/PropertyHelper.php
  src/View/Helper/SchemaHelper.php
  tests/TestCase/Form/ControlTypeTest.php
Labels: bug, Priority - High, release:patch
