Repository bedita/manager, pull requests merged in 2023-03, with the labels that each got.

#960 Minor fix: use flash error instead of warning to show error messages
  src/Controller/Component/ThumbsComponent.php
Labels: Priority - Low, release:patch

#958 Pass only changed attributes in object types API calls
  config/schema_properties.php
  src/Controller/Model/ObjectTypesController.php
  templates/Pages/Model/ObjectTypes/view.twig
Labels: Priority - Normal, release:patch

#961 Enable `vue-loader`
  package.json
  resources/js/app/components/json-fields/key-value-list.vue
  resources/js/app/components/json-fields/string-list.vue
  webpack.config.js
  yarn.lock
Labels: dependencies, integration

#963 UI show modal for flash messages (when config `Flash.modal = true`)
  config/app_local.example.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/dialog/dialog.js
  resources/js/app/components/dialog/dialog.scss
  resources/js/app/components/flash-message.js
  resources/js/app/components/flash-message.vue
  src/Controller/Component/ThumbsComponent.php
  templates/Element/flash/flash.scss
  templates/Element/flash/flash.twig
  tests/TestCase/Controller/Component/ThumbsComponentTest.php
Labels: UI / UX, release:patch

#966 Uri field full width
  resources/js/app/components/uri-input.js
  templates/Element/Form/form.scss
Labels: feature, Priority - Normal, UI / UX, release:patch

#965 Review object properties modeling layout
  config/properties.php
  config/schema_properties.php
  resources/js/app/app.js
  resources/js/app/components/object-property/object-properties.vue
  resources/js/app/components/object-property/object-property-add.vue
  resources/js/app/components/object-property/object-property.vue
  resources/js/app/components/property-view/property-view.js
  resources/js/app/pages/modules/view.js
  src/Controller/Model/ObjectTypesController.php
  templates/Pages/Model/ObjectTypes/view.twig
  tests/TestCase/Controller/Model/ObjectTypesControllerTest.php
Labels: UI / UX, release:patch

#968 Add vue-loader to webpack plugins conf
  webpack.config.plugin.js
Labels: javascript, release:patch

#973 Use serial mode upload for dragndrop files to avoid uname error
  resources/js/app/components/drop-upload.js
  resources/js/app/helpers/view.js
Labels: feature, javascript, release:patch

#974 Roles groups and roles escalation management
  config/app_local.example.php
  resources/js/app/components/relation-view/roles-list-view.js
  resources/js/app/components/relation-view/roles-list-view.vue
  src/Identifier/Resolver/ApiResolver.php
  templates/Element/Form/roles.twig
Labels: feature, UI / UX, release:patch

#975 Fix translations custom controls + refactor UI
  resources/js/app/components/json-fields/string-list.vue
  resources/js/app/pages/modules/view.js
  src/Form/CustomComponentControl.php
  src/View/Helper/PropertyHelper.php
  templates/Element/translation.twig
  templates/Pages/Modules/_modules-view.scss
  tests/TestCase/Form/CustomComponentControlTest.php
  tests/TestCase/View/Helper/PropertyHelperTest.php
Labels: bug, Priority - High, refactor, release:patch

#976 Fix auto translate string-list and enhance auto translate logic
  resources/js/app/components/json-fields/string-list.vue
  resources/js/app/helpers/api-translation.js
  resources/js/app/pages/modules/view.js
  templates/Element/translation.twig
Labels: bug, Priority - High, javascript, release:patch
