Repository bedita/manager, pull requests merged in 2023-01, with the labels that each got.

#913 Bump json5 to version 1.0.2
  yarn.lock
Labels: Priority - Normal, dependencies, javascript

#915 Icons on buttons and anchors
  resources/js/app/components/category/category.js
  resources/js/app/components/object-property/object-property.js
  templates/Element/Admin/index_content.twig
  templates/Element/Admin/sidebar.twig
  templates/Element/Form/bulk_category.twig
  templates/Element/Form/bulk_custom.twig
  templates/Element/Form/bulk_export.twig
  templates/Element/Form/bulk_position.twig
  templates/Element/Form/bulk_properties.twig
  templates/Element/Form/bulk_trash.twig
  templates/Element/Form/related_item.twig
  templates/Element/Form/relation.twig
  templates/Element/Menu/sidebar.twig
  templates/Element/Model/index_content.twig
  templates/Element/Model/sidebar_links.twig
  templates/Element/Modules/index_table_row.twig
  templates/Element/Modules/index_tags.twig
  templates/Element/Panel/relations_add.twig
  templates/Element/translation.twig
  templates/Pages/Error/error400.twig
  templates/Pages/Error/error500.twig
  templates/Pages/Login/login.twig
  templates/Pages/Model/ObjectTypes/view.twig
  templates/Pages/Model/PropertyTypes/index.twig
  templates/Pages/Model/Relations/index.twig
  templates/Pages/Model/Relations/view.twig
  templates/Pages/Modules/index.twig
  templates/Pages/Modules/view.twig
  templates/Pages/Trash/index.twig
  templates/Pages/UserProfile/view.twig
Labels: UI / UX, release:minor

#917 Drop files upload: title from filename
  resources/js/app/components/drop-upload.js
Labels: feature, Priority - Normal, release:patch

#918 Fix fonts path in css
  webroot/css/be-icons-font.css
Labels: bug, release:patch

#919 Confirm dialog loader and disable buttons
  resources/js/app/components/dialog/dialog.js
Labels: feature, UI / UX, javascript, release:patch

#923 Add created and publish_date to children_order combo
  config/bedita-api-version.ini
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  package.json
  resources/js/app/app.js
  resources/js/app/components/relation-view/relation-view.js
  resources/js/app/helpers/view.js
  src/Form/Options.php
  templates/Element/Form/related_item.twig
  templates/Element/Form/relation.twig
  tests/TestCase/Form/OptionsTest.php
  tests/TestCase/View/Helper/SystemHelperTest.php
  yarn.lock
Labels: feature, Priority - High, release:minor

#924 Fix relations add
  resources/js/app/components/relation-view/relations-add.js
Labels: bug, Priority - High, javascript, release:patch

#916 File upload: check file type and size. Show preview if it is an image
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/drop-upload.js
  resources/js/app/components/form-file-upload.js
  resources/js/app/components/property-view/property-view.js
  resources/js/app/components/relation-view/relations-add.js
  resources/js/app/helpers/view.js
  resources/js/app/pages/import/index.js
  src/View/Helper/LayoutHelper.php
  src/View/Helper/SystemHelper.php
  templates/Element/Form/form_file_upload.twig
  templates/Element/Form/media.twig
  templates/Element/Panel/relations_add.twig
  templates/Pages/Import/index.twig
  tests/TestCase/View/Helper/LayoutHelperTest.php
  tests/TestCase/View/Helper/SystemHelperTest.php
Labels: feature, Priority - Normal, UI / UX, javascript, release:patch

#933 Fix error saving new relation with empty params
  config/schema_properties.php
  src/Controller/Model/ModelBaseController.php
Labels: release:patch

#934 Add latest vanilla-jsoneditor
  package.json
  resources/js/app/components/json-editor-input.js
  yarn.lock
Labels: dependencies, javascript
