Repository bedita/manager, pull requests merged in 2023-04, with the labels that each got.

#979 Refactor: register component Icon in app.js
  resources/js/app/app.js
  resources/js/app/components/category/category.js
  resources/js/app/components/date-ranges-list/date-ranges-list.js
  resources/js/app/components/dialog/dialog.js
  resources/js/app/components/drop-upload.js
  resources/js/app/components/filter-box.js
  resources/js/app/components/flash-message.vue
  resources/js/app/components/form-file-upload.js
  resources/js/app/components/horizontal-tab-view.js
  resources/js/app/components/index-cell/index-cell.js
  resources/js/app/components/json-fields/string-list.vue
  resources/js/app/components/locations-view/location-view.js
  resources/js/app/components/login-password/login-password.js
  resources/js/app/components/menu.js
  resources/js/app/components/object-nav/object-nav.vue
  resources/js/app/components/panel-view.js
  resources/js/app/components/property-view/property-view.js
  resources/js/app/components/relation-view/relation-view.js
  resources/js/app/components/relation-view/relations-add.js
  resources/js/app/components/secret/secret.js
  resources/js/app/components/tag-form/tag-form.js
  resources/js/app/components/thumbnail/thumbnail.vue
  resources/js/app/pages/admin/appearance.js
  resources/js/app/pages/admin/index.js
  resources/js/app/pages/dashboard/index.js
  resources/js/app/pages/import/index.js
  resources/js/app/pages/model/index.js
  resources/js/app/pages/modules/index.js
  resources/js/app/pages/modules/view.js
Labels: Priority - High, javascript, release:patch

#981 Javascript helper function debounce
  resources/js/app/helpers/view.js
Labels: feature, javascript, release:patch

#982 Show object title, module name and project name in `<title>`
  src/View/Helper/LayoutHelper.php
  templates/Pages/Modules/view.twig
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: feature, release:patch

#983 Show resource change in edit
  resources/js/app/app.js
  resources/js/app/pages/modules/view.js
  src/View/Helper/LayoutHelper.php
  templates/Element/Menu/sidebar.scss
  tests/TestCase/View/Helper/LayoutHelperTest.php
  webpack.config.js
  webroot/svg/iconFloppy.svg
Labels: feature, Priority - High, UI / UX, javascript, release:patch

#978 Folders permissions
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/app.js
  resources/js/app/components/object-property/object-property.vue
  resources/js/app/components/permission/permission.vue
  resources/js/app/components/permissions/permissions.vue
  resources/js/app/components/property-view/property-view.js
  resources/js/app/components/tree-view/tree-view.vue
  src/Controller/Component/PropertiesComponent.php
  src/View/Helper/PermsHelper.php
  templates/Element/Form/permissions.twig
  templates/Element/Form/trees.twig
  templates/Pages/Modules/index.twig
  templates/Pages/Modules/view.twig
  tests/TestCase/Controller/Component/PropertiesComponentTest.php
  tests/TestCase/View/Helper/PermsHelperTest.php
Labels: feature, Priority - High, UI / UX, javascript, release:minor

#985 Fix tree-view defaults
  resources/js/app/components/tree-view/tree-view.vue
Labels: bug, Priority - High, UI / UX, release:patch

#986 Show or hide locked folders in `tree-view`
  config/routes.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/permission-toggle/permission-toggle.vue
  resources/js/app/components/permissions/permissions.vue
  resources/js/app/components/property-view/property-view.js
  resources/js/app/components/tree-view/tree-view.vue
  resources/js/app/pages/modules/index.js
  src/Controller/ModulesController.php
  src/Controller/SessionController.php
  templates/Element/Form/permissions.twig
  templates/Element/Form/trees.twig
  templates/Pages/Modules/index.twig
  tests/TestCase/Controller/SessionControllerTest.php
Labels: feature, Priority - High, release:patch

#988 Save folder permissions
  resources/js/app/components/permissions/permissions.vue
  resources/js/app/pages/modules/view.js
  src/Controller/Admin/RolesController.php
  src/Controller/ModulesController.php
  src/Utility/PermissionsTrait.php
  templates/Element/Form/permissions.twig
  tests/TestCase/Controller/Admin/RolesControllerTest.php
  tests/TestCase/Utility/PermissionsTraitTest.php
Labels: feature, Priority - High, release:patch

#991 Clone streams when cloning media objects
  config/bedita-api-version.ini
  src/Controller/Component/CloneComponent.php
  src/Controller/ModulesController.php
  tests/TestCase/Controller/Component/CloneComponentTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
  tests/TestCase/View/Helper/SystemHelperTest.php
Labels: feature, Priority - High, release:minor

#989 ElementHelper for special template paths
  src/View/AppView.php
  src/View/Helper/ElementHelper.php
  src/View/Helper/LayoutHelper.php
  templates/Element/Form/group_properties.twig
  templates/Element/Form/relation.twig
  templates/Element/Form/roles.twig
  templates/Element/Modules/sidebar.twig
  templates/Pages/Modules/index.twig
  templates/Pages/Modules/view.twig
  tests/TestCase/View/Helper/ElementHelperTest.php
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: feature, Priority - High, refactor, release:patch
