Repository bedita/manager, pull requests merged in 2023-07, with the labels that each got.

#1019 Use `null` and not `"null"` when saving boolean nullable properties
  src/Controller/AppController.php
  src/Form/Control.php
  src/Form/Form.php
  tests/TestCase/Controller/AppControllerTest.php
  tests/TestCase/Form/ControlTest.php
Labels: bug, Priority - High, release:patch

#1018 Manual release with Release workflow
  .github/workflows/release.yml
Labels: integration

#1015 Save related object when no id
  resources/js/app/components/locations-view/location-view.vue
  resources/js/app/components/locations-view/locations-view.vue
  src/Controller/Component/ModulesComponent.php
  tests/TestCase/Controller/Component/ModulesComponentTest.php
Labels: feature, Priority - High, release:patch

#1021 Fix save related data including meta
  src/Controller/Component/ModulesComponent.php
Labels: bug, Priority - High, release:patch

#1022 Fix paginated position
  resources/js/app/components/relation-view/relation-view.js
  resources/js/app/mixins/paginated-content.js
Labels: bug, Priority - Critical, release:patch

#1024 Avoid empty view groups
  templates/Element/Form/other_properties.twig
Labels: UI / UX, release:patch

#1023 Refactor styles
  resources/styles/_elements.scss
  resources/styles/_utility_classes.scss
  templates/Element/FilterBox/filter_box.scss
  templates/Element/FilterBox/filter_box_common.twig
  templates/Pages/Login/login.twig
Labels: UI / UX

#1025 Use `null` as default attribute value on new objects
  src/Controller/ModulesController.php
Labels: release:patch

#1026 Fix warning on save
  .github/workflows/php.yml
  src/Controller/AppController.php
  tests/TestCase/Controller/AppControllerTest.php
Labels: feature, release:patch

#1029 Remove unnecessary 404 on missing `showForbidden` session var
  resources/js/app/components/permission-toggle/permission-toggle.vue
  src/Controller/SessionController.php
  tests/TestCase/Controller/SessionControllerTest.php
Labels: javascript, refactor

#1031 Administration "Objects history" and "User accesses
  config/routes.php
  resources/js/app/app.js
  resources/js/app/components/objects-history/objects-history.vue
  resources/js/app/components/pagination-navigation/pagination-navigation.vue
  resources/js/app/components/user-accesses/user-accesses.vue
  resources/js/app/helpers/view.js
  src/Controller/Admin/ObjectsHistoryController.php
  src/Controller/Admin/UserAccessesController.php
  src/View/Helper/LayoutHelper.php
  templates/Element/Admin/sidebar.twig
  templates/Pages/Admin/ObjectsHistory/index.twig
  templates/Pages/Admin/UserAccesses/index.twig
  tests/TestCase/Controller/Admin/ObjectsHistoryControllerTest.php
  tests/TestCase/Controller/Admin/UserAccessesControllerTest.php
Labels: feature, release:minor

#1011 Translatable fields from schema
  config/app_local.example.php
  resources/js/app/components/object-property/object-properties.vue
  resources/js/app/components/object-property/object-property.vue
  src/Controller/Model/ObjectTypesController.php
  src/View/Helper/SchemaHelper.php
  templates/Element/Form/related_translations.twig
  templates/Element/translation.twig
  templates/Pages/Model/ObjectTypes/view.twig
  tests/TestCase/Controller/Model/ObjectTypesControllerTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: feature, refactor, release:patch

#1033 Fix locked by parents on empty perms
  src/View/Helper/PermsHelper.php
  tests/TestCase/View/Helper/PermsHelperTest.php
Labels: bug, release:patch
