Repository bedita/manager, pull requests merged in 2023-05, with the labels that each got.

#993 Fix categories template path
  src/View/Helper/ElementHelper.php
  tests/TestCase/View/Helper/ElementHelperTest.php
Labels: bug, Priority - High, release:patch

#992 Fix save permissions considering inherited
  src/Controller/ModulesController.php
  src/Utility/PermissionsTrait.php
  tests/TestCase/Utility/PermissionsTraitTest.php
Labels: bug, Priority - Normal, release:patch

#994 Enhance import page
  config/app_local.example.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/app.js
  resources/js/app/components/import/jobs.vue
  resources/js/app/components/import/result.vue
  resources/js/app/components/json-editor/json-editor.vue
  resources/js/app/pages/import/index.js
  resources/js/app/pages/import/index.vue
  src/Controller/ImportController.php
  templates/Pages/Import/import.scss
  templates/Pages/Import/index.twig
  tests/TestCase/Controller/ImportControllerTest.php
Labels: Priority - High, UI / UX, release:patch

#995 Refactor and fix import index
  resources/js/app/pages/import/index.vue
Labels: bug, Priority - High, javascript, release:patch

#999 Use `async_jobs` endpoint
  src/Controller/Component/ModulesComponent.php
  src/Controller/DashboardController.php
  src/Controller/ImportController.php
  src/Core/Filter/ImportFilter.php
  src/Utility/SchemaTrait.php
  templates/Pages/Dashboard/index.twig
  templates/Pages/Import/index.twig
  tests/TestCase/Controller/Component/ModulesComponentTest.php
  tests/TestCase/Controller/DashboardControllerTest.php
  tests/TestCase/Controller/ImportControllerTest.php
  tests/TestCase/Core/Filter/ImportFilterTest.php
  tests/TestCase/Utility/SchemaTraitTest.php
Labels: feature, Priority - High, release:minor

#998 Attempt to improve locations autocomplete
  resources/js/app/components/locations-view/location-view.js
  templates/Element/Form/locations.scss
Labels: Priority - Normal, UI / UX, release:patch

#1001 Bump socket.io-parser from 4.2.1 to 4.2.3
  yarn.lock
Labels: dependencies, javascript

#1002 Fix trash permanently delete single object
  templates/Element/Modules/index_table_row.twig
Labels: bug, Priority - Normal, release:patch

#1003 Use checkout v3 and setup-node v3 in javascript github workflow
  .github/workflows/javascript.yml
Labels: javascript, integration
