Repository bedita/manager, pull requests merged in 2024-06, with the labels that each got.

#1129 Refactor: more flexible richeditor config
  config/app_local.example.php
  resources/js/app/directives/richeditor.js
Labels: feature, javascript, release:patch

#1123 Enhance translations index
  resources/js/app/app.js
  src/View/Helper/LayoutHelper.php
  templates/Pages/Translations/index.twig
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: feature, release:minor

#1130 Date ranges data: fix params on save
  .gitignore
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/app.js
  resources/js/app/components/date-range/date-range.vue
  resources/js/app/components/date-ranges-view/date-ranges-view.vue
  resources/js/app/components/property-view/property-view.js
  src/Controller/AppController.php
  src/Utility/DateRangesTools.php
  tests/TestCase/Controller/AppControllerTest.php
  tests/TestCase/Controller/TreeControllerTest.php
  tests/TestCase/Utility/DateRangesToolsTest.php
Labels: bug, release:patch

#1125 Folders switch view type between tree and list
  resources/js/app/app.js
  src/View/Helper/LayoutHelper.php
  templates/Element/Modules/list.twig
  templates/Element/Modules/sidebar.twig
  templates/Element/Modules/tree.twig
  templates/Pages/Modules/index.twig
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: feature, release:minor

#1133 Fix trashcan error: default to empty array if no custom filter is defined
  templates/Element/Modules/index_header.twig
Labels: bug, release:patch

#1135 Date range `params.weekdays` as json
  resources/js/app/components/date-ranges-view/date-ranges-view.vue
  src/Utility/DateRangesTools.php
  tests/TestCase/Utility/DateRangesToolsTest.php
Labels: bug, release:patch

#1131 Fix route and form for new resource creation
  config/routes.php
  resources/js/app/mixins/paginated-content.js
  templates/Element/Form/categories.twig
  tests/TestCase/Controller/Model/ModelBaseControllerTest.php
Labels: Priority - Normal, release:patch

#1140 Javascript dependencies update + node 22.x in javascript github workflow
  .github/workflows/javascript.yml
  yarn.lock
Labels: javascript, integration

#1139 Max resolution check for images upload
  config/app_local.example.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/drop-upload.vue
  resources/js/app/components/form-file-upload.js
  resources/js/app/components/property-view/property-view.js
  resources/js/app/components/relation-view/relations-add.js
  resources/js/app/helpers/view.js
  src/View/Helper/SystemHelper.php
  tests/TestCase/View/Helper/SystemHelperTest.php
Labels: feature, release:minor

#1141 Check image resolution: warning when image could not load
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/helpers/view.js
Labels: javascript, release:patch

#1142 Fix locations view for new object
  resources/js/app/components/locations-view/locations-view.vue
Labels: bug, Priority - High, release:patch

#1144 Schema fetch all categories per type
  src/Controller/Component/SchemaComponent.php
Labels: bug, release:patch

#1137 Refactor categories to handle parents per type
  resources/js/app/components/category-form/category-form.vue
  src/Controller/Component/CategoriesComponent.php
  templates/Element/Modules/index_categories.twig
  templates/Pages/Model/Categories/index.twig
  tests/TestCase/Controller/Component/CategoriesComponentTest.php
  tests/TestCase/Utility/DateRangesToolsTest.php
Labels: UI / UX, refactor, release:minor

#1145 Fix object-property component styles
  resources/js/app/components/object-property/object-property.vue
Labels: UI / UX

#1146 Fix save date ranges from fast creation form
  src/Controller/AppController.php
Labels: bug, release:patch

#1138 Placeholders parameters
  config/app_local.example.php
  config/i18n_strings.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/app.js
  resources/js/app/components/event-bus.vue
  resources/js/app/components/placeholder-list/placeholder-list.vue
  resources/js/app/components/placeholder-list/placeholder-params.vue
  resources/js/app/components/property-view/property-view.js
  resources/js/app/directives/richeditor.js
  resources/js/app/plugins/tinymce/placeholders.js
  src/View/Helper/LayoutHelper.php
  src/View/Helper/SystemHelper.php
  templates/Element/Form/group_properties.twig
  tests/TestCase/View/Helper/LayoutHelperTest.php
  tests/TestCase/View/Helper/SystemHelperTest.php
Labels: feature, UI / UX, release:minor

#1150 Delete stream per media
  src/Controller/TrashController.php
  tests/TestCase/Controller/BaseControllerTest.php
  tests/TestCase/Controller/TrashControllerTest.php
Labels: bug, release:patch

#1136 Module items count
  resources/styles/_elements.scss
  src/Controller/DashboardController.php
  src/Controller/Model/TagsController.php
  src/Controller/ModulesController.php
  src/Controller/TrashController.php
  src/Utility/CacheTools.php
  src/View/Helper/LayoutHelper.php
  templates/Pages/Dashboard/index.twig
  tests/TestCase/Controller/DashboardControllerTest.php
  tests/TestCase/Utility/CacheToolsTest.php
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: feature, UI / UX, release:minor

#1151 Style fix: users count background
  templates/Pages/Dashboard/index.twig
Labels: UI / UX, release:patch

#1152 Fix modules count
  src/Utility/CacheTools.php
  src/View/Helper/LayoutHelper.php
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: bug, release:patch

#1153 Skip save if no data changed
  src/Controller/AppController.php
  src/Controller/CategoriesController.php
  src/Controller/Component/CategoriesComponent.php
  src/Controller/Model/CategoriesController.php
  src/Controller/Model/TagsController.php
  src/Controller/ModulesController.php
  tests/TestCase/Controller/AppControllerTest.php
  tests/TestCase/Controller/Component/CategoriesComponentTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
Labels: feature, release:minor

#1154 Remove stream on delete, retrocompatibility
  src/Controller/TrashController.php
Labels: refactor, release:patch
