Repository bedita/manager, pull requests merged in 2024-02, with the labels that each got.

#1081 Fix duplicated fields in translation form
  src/View/Helper/SchemaHelper.php
Labels: bug, Priority - High, release:patch

#1082 Language selection with autocomplete dropdown
  resources/js/app/app.js
  resources/js/app/components/language-selector/language-selector.vue
  resources/js/app/components/property-view/property-view.js
  resources/js/app/pages/modules/view.vue
  templates/Element/Form/related_translations.twig
  templates/Element/translation.twig
  templates/Pages/Translations/index.twig
Labels: feature, UI / UX, refactor, release:patch

#1083 Dashboard section to go to object by id or uname
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/pages/dashboard/index.js
  templates/Pages/Dashboard/index.twig
Labels: feature, release:patch

#1084 Add `Microsoft Entra ID / Azure AD` login support
  composer.json
  config/app.php
Labels: feature, Priority - High, release:minor

#1088 Fix index: get objects filtered by type
  src/Controller/ModulesController.php
Labels: bug, Priority - High, release:patch

#1090 CalendarHelper::list null date ranges
  src/View/Helper/CalendarHelper.php
  tests/TestCase/View/Helper/CalendarHelperTest.php
Labels: bug, release:patch

#1089 Restore getObjects in Modules index
  src/Controller/ModulesController.php
Labels: bug, Priority - High, release:patch
