Repository bedita/manager, pull requests merged in 2024-11, with the labels that each got.

#1199 Fix weekdays when empty
  resources/js/app/components/date-range/date-range.vue
Labels: bug, release:patch

#1200 Fix date range `all_day`
  resources/js/app/components/date-range/date-range.vue
Labels: bug, release:patch

#1201 Fix date range use UTC on all_day true
  resources/js/app/components/date-range/date-range.vue
Labels: bug, release:patch

#1203 Fix Tinymce branding true
  resources/js/app/directives/richeditor.js
Labels: javascript, release:patch

#1202 Richtext custom toolbar per field + custom config per field
  config/app_local.example.php
  resources/js/app/components/index-cell/index-cell.js
  resources/js/app/components/index-cell/index-cell.vue
  resources/js/app/components/recent-activity/recent-activity.vue
  resources/js/app/directives/richeditor.js
  src/Form/Control.php
  src/View/Helper/LayoutHelper.php
  src/View/Helper/SchemaHelper.php
  templates/Element/Modules/index_table_row.twig
  templates/Layout/default.twig
  templates/Layout/error.twig
  templates/Pages/Modules/view.twig
  tests/TestCase/View/Helper/LayoutHelperTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: feature, release:minor

#1205 Clone relations with meta (and relation parameters)
  src/Controller/Component/CloneComponent.php
Labels: release:patch

#1206 Tune tinymce conf
  resources/js/app/directives/richeditor.js
  templates/Element/Form/related_item.twig
  templates/Pages/Translations/index.twig
Labels: bug, UI / UX, release:patch
