Repository bedita/manager, pull requests merged in 2024-10, with the labels that each got.

#1188 Edit children parameters
  config/app_local.example.php
  config/relations.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/app.js
  resources/js/app/components/edit-children-params.vue
  resources/js/app/components/edit-relation-param.vue
  resources/js/app/components/relation-view/relation-view.vue
  src/Controller/Component/SchemaComponent.php
  templates/Element/Form/related_item.twig
  templates/Element/Form/relation.twig
  tests/TestCase/Controller/Component/SchemaComponentTest.php
Labels: feature, release:minor

#1190 Do not save numeric uname
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  src/Controller/ModulesController.php
  tests/TestCase/Controller/ModulesControllerTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: bug, release:patch

#1193 Show user roles in user profile + fix roles priority check
  resources/js/app/components/relation-view/roles-list-view.vue
  src/Identifier/Resolver/ApiResolver.php
  templates/Element/Form/roles.twig
  templates/Pages/UserProfile/view.twig
Labels: feature, UI / UX, release:patch

#1194 Associations from config
  config/app_local.example.php
  src/Controller/Component/PropertiesComponent.php
Labels: integration

#1191 Sort button for related contents
  config/app_local.example.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/app.js
  resources/js/app/components/relation-view/relation-view.vue
  resources/js/app/components/sort-related/sort-related.vue
  src/View/Helper/SystemHelper.php
  templates/Element/Form/relation.twig
  tests/TestCase/View/Helper/SystemHelperTest.php
Labels: feature, release:minor

#1195 Admin statistics
  .github/workflows/php.yml
  config/routes.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  package.json
  resources/js/app/app.js
  resources/js/app/components/charts/bar-chart.vue
  resources/js/app/pages/admin/statistics.vue
  src/Controller/Admin/StatisticsController.php
  src/Controller/Model/ObjectTypesController.php
  src/View/Helper/AdminHelper.php
  src/View/Helper/LayoutHelper.php
  templates/Element/Admin/sidebar.twig
  templates/Pages/Admin/Statistics/index.twig
  tests/TestCase/Controller/Admin/StatisticsControllerTest.php
  tests/TestCase/View/Helper/AdminHelperTest.php
  yarn.lock
Labels: feature, release:minor

#1198 Remove unnecessary failed save form data session handling
  src/Controller/Component/ModulesComponent.php
  src/Controller/ModulesController.php
  tests/TestCase/Controller/Component/ModulesComponentTest.php
Labels: bug, release:patch
