Repository bedita/manager, pull requests merged in 2024-05, with the labels that each got.

#1110 Search in visible positions of object detail
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/property-view/property-view.js
  resources/js/app/components/tree-view/tree-view.vue
  resources/styles/_utility_classes.scss
  templates/Element/Form/trees.twig
Labels: feature, Priority - High, release:minor

#1108 Relation related items id and uname
  .gitignore
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/app.js
  resources/js/app/components/clipboard-item/clipboard-item.vue
  resources/js/app/components/property-view/property-view.js
  resources/js/app/components/relation-view/relation-view.js
  templates/Element/Form/related_item.twig
Labels: feature, Priority - High, release:patch

#1109 Handle missing `Project.config.I18n` configuration
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  templates/Element/Form/related_translations.twig
Labels: bug, release:patch

#1111 Search items by id or uname in side panel
  locales/default.pot
  locales/en_US/default.po
  resources/js/app/components/filter-box.js
  templates/Element/FilterBox/filter_box.twig
  templates/Element/FilterBox/filter_box_common.twig
  templates/Element/Panel/relations_add.twig
Labels: feature, release:minor

#1112 Fix ClipboardItem in relations-add
  resources/js/app/components/relation-view/relations-add.js
Labels: bug, release:patch, integration

#1102 Multiple upload page for audio, files, images, video
  config/routes.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/drop-upload.vue
  resources/js/app/pages/modules/index.js
  resources/styles/_elements.scss
  src/Controller/MultiuploadController.php
  src/View/Helper/SystemHelper.php
  templates/Element/Modules/sidebar.twig
  templates/Pages/Multiupload/index.twig
  tests/TestCase/Controller/MultiuploadControllerTest.php
Labels: feature, release:minor

#1115 Add visual blocks to TinyMCE
  resources/js/app/directives/richeditor.js
  resources/richeditor.lazy.scss
Labels: feature, Priority - Normal, release:patch

#1117 Fix richtext undesired content by disabling TinyMCE unload triggers
  resources/js/app/directives/richeditor.js
Labels: bug, release:patch

#1116 Customize calendar label and options
  resources/js/app/components/date-ranges-view/date-ranges-view.vue
  templates/Element/Form/calendar.twig
Labels: feature, release:patch

#1114 Object relation data new "Export filtered" button
  config/routes.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/relation-view/relation-view.js
  src/Controller/ExportController.php
  templates/Element/FilterBox/filter_box_common.twig
  templates/Element/Form/relation.twig
  tests/TestCase/Controller/ExportControllerTest.php
Labels: feature, release:patch

#1113 Enhance Categories UI in object view
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/app.js
  resources/js/app/components/object-categories/object-categories.vue
  resources/js/app/components/property-view/property-view.js
  src/View/AppView.php
  templates/Element/Form/categories.twig
Labels: UI / UX, refactor, release:patch

#1119 Fix Admin Appearance style sheets
  .gitignore
  resources/js/app/pages/admin/appearance.vue
Labels: bug, UI / UX, release:patch

#1120 UI minor improvements in object view
  resources/js/app/components/object-categories/object-categories.vue
  resources/js/app/components/relation-view/relations-add.js
  templates/Element/Form/related_item.twig
  templates/Element/Form/relations.scss
  templates/Pages/Modules/_modules-view.scss
Labels: UI / UX, release:patch

#1122 Fix save categories when none is checked
  resources/js/app/components/object-categories/object-categories.vue
  src/Controller/AppController.php
  tests/TestCase/Controller/AppControllerTest.php
Labels: bug, release:patch

#1124 Object history: view all changes
  config/routes.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/history/history-changes.vue
  resources/js/app/components/property-view/property-view.js
  src/Controller/Component/HistoryComponent.php
  src/Controller/HistoryController.php
  templates/Element/Form/history.twig
  tests/TestCase/Controller/Component/HistoryComponentTest.php
  tests/TestCase/Controller/HistoryControllerTest.php
Labels: bug, release:patch

#1126 Fix styles on relations filter-box
  templates/Element/Form/relations.scss
Labels: UI / UX, release:patch

#1127 Hide categories and tags in relation filters
  templates/Element/FilterBox/filter_box_common.twig
  templates/Element/Form/relations.scss
Labels: UI / UX, release:patch

#1121 Filter label customizable
  src/View/Helper/SchemaHelper.php
  templates/Element/FilterBox/filter_box.scss
  templates/Element/FilterBox/filter_box_common.twig
  templates/Element/Form/relation.twig
  templates/Element/Modules/index_header.twig
  templates/Element/Panel/relations_add.twig
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: feature, release:minor
