Repository bedita/manager, pull requests merged in 2024-12, with the labels that each got.

#1207 Position tree: show active positions
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/property-view/property-view.js
  resources/js/app/components/tree-view/tree-view.vue
  templates/Element/Form/trees.twig
Labels: feature, release:patch

#1208 Prepare release 5: BEdita API >= 5.36.0, php >= 8.3, node >= 20 + refactor clone
  .github/workflows/javascript.yml
  .github/workflows/php.yml
  .github/workflows/release.yml
  .gitignore
  .scrutinizer.yml
  Dockerfile
  README.md
  composer.json
  config/app_local.example.php
  config/bedita-api-version.ini
  package.json
  resources/js/app/app.js
  resources/js/app/components/property-view/property-view.js
  resources/js/app/components/tree-view/tree-view.vue
  src/Command/TranslateCommand.php
  src/Controller/Component/CategoriesComponent.php
  src/Controller/Component/CloneComponent.php
  src/Controller/ModulesController.php
  src/Controller/TrashController.php
  src/View/Helper/SchemaHelper.php
  templates/Element/Form/trees.twig
  tests/TestCase/Controller/Admin/StatisticsControllerTest.php
  tests/TestCase/Controller/Admin/SystemInfoControllerTest.php
  tests/TestCase/Controller/Component/CloneComponentTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
  tests/TestCase/Controller/TrashControllerTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
  tests/TestCase/View/Helper/SystemHelperTest.php
  tests/bootstrap.php
  yarn.lock
Labels: dependencies, refactor, release:major, integration

#1211 Media provider form + Subtitles in audio / video
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/app.js
  resources/js/app/components/media-item/media-item.vue
  resources/js/app/components/property-view/property-view.js
  src/Controller/Component/PropertiesComponent.php
  src/View/Helper/LayoutHelper.php
  templates/Element/Form/captions.twig
  templates/Element/Form/media.twig
  templates/Element/Form/other_properties.twig
  tests/TestCase/Controller/Component/PropertiesComponentTest.php
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: feature, release:minor
