Repository bedita/manager, pull requests merged in 2024-03, with the labels that each got.

#1092 Tree optimizations with cache and more compact data
  config/app.php
  config/routes.php
  resources/js/app/components/folder-picker/folder-picker.js
  resources/js/app/components/tree-view/tree-view.vue
  src/Application.php
  src/Controller/Component/ModulesComponent.php
  src/Controller/ModulesController.php
  src/Controller/TreeController.php
  src/Event/TreeCacheEventHandler.php
  tests/TestCase/Controller/TreeControllerTest.php
  tests/TestCase/Event/TreeCacheEventHandlerTest.php
Labels: feature, Priority - High, refactor, release:minor

#1094 Optimize tree loading
  config/routes.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/folder-picker/folder-picker.js
  resources/js/app/components/tree-view/tree-view.vue
  src/Controller/TreeController.php
  tests/TestCase/Controller/TreeControllerTest.php
Labels: feature, Priority - High, UI / UX, release:patch

#1095 Tree fix load folder
  resources/js/app/components/tree-view/tree-view.vue
Labels: bug, release:patch

#1096 Fix tree parents metadata
  resources/js/app/components/tree-view/tree-view.vue
  src/Controller/TreeController.php
  src/Event/TreeCacheEventHandler.php
  tests/TestCase/Event/TreeCacheEventHandlerTest.php
Labels: bug, Priority - High, release:patch

#1099 Fix svg images do not need thumbnails
  templates/Element/Form/media.twig
Labels: bug, release:patch

#1101 Svg in media list, do not use thumbnails
  templates/Element/Form/media.twig
  templates/Element/Modules/thumb.twig
Labels: bug, release:patch
