Repository bedita/manager, pull requests merged in 2024-01, with the labels that each got.

#1075 Update typos package
  yarn.lock
Labels: bug, Priority - Normal, release:patch

#1078 Fix boolean nullable search filter
  resources/js/app/components/filter-box.js
Labels: bug, javascript, release:patch

#1077 Use concrete object types in side Panel
  resources/js/app/components/relation-view/relations-add.js
  resources/js/app/plugins/tinymce/placeholders.js
  src/Controller/ModulesController.php
  src/View/Helper/LayoutHelper.php
  src/View/Helper/SchemaHelper.php
  templates/Element/Panel/relations_add.twig
  tests/TestCase/View/Helper/LayoutHelperTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: feature, refactor, release:patch

#1079 Input number attribute step
  src/Form/Control.php
  src/Form/ControlType.php
  src/View/Helper/SchemaHelper.php
  tests/TestCase/Form/ControlTypeTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: bug, Priority - High, release:patch

#1080 Use objects endpoint to search by type
  resources/js/app/components/relation-view/roles-list-view.vue
  resources/styles/_utility_classes.scss
  src/Controller/ModulesController.php
  tests/TestCase/Controller/ModulesControllerTest.php
Labels: bug, Priority - High, release:patch
