Repository bedita/manager, pull requests merged in 2025-01, with the labels that each got.

#1212 Fix side panel search filter
  resources/js/app/components/filter-box.vue
  src/Controller/ModulesController.php
  src/View/Helper/SchemaHelper.php
  tests/TestCase/Controller/ModulesControllerTest.php
Labels: bug, release:patch

#1213 Sortable columns in module index, avoid `[400] Unsupported sorting field`
  src/View/Helper/SchemaHelper.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: bug, release:patch

#1215 Remove api call in trash delete
  src/Controller/TrashController.php
Labels: refactor

#1214 Avoid sorting custom props from model
  src/Controller/Component/SchemaComponent.php
  src/Controller/ModulesController.php
  src/Controller/TranslationsController.php
  src/View/Helper/SchemaHelper.php
  tests/TestCase/Controller/Component/SchemaComponentTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: release:patch

#1192 Save and reset related
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/components/relation-view/relation-view.vue
  templates/Element/Form/relation.twig
Labels: feature, release:minor

#1220 Customize elements for upload: multi upload page and drop upload section
  config/app_local.example.php
  resources/js/app/app.js
  resources/js/app/helpers/view.js
  resources/js/app/mixins/paginated-content.js
  resources/js/app/pages/modules/index.js
  src/Controller/ModulesController.php
  src/View/Helper/ElementHelper.php
  templates/Element/Form/dropupload.twig
  templates/Element/Form/multiupload.twig
  templates/Element/Form/relation.twig
  templates/Pages/Multiupload/index.twig
  tests/TestCase/View/Helper/ElementHelperTest.php
Labels: feature, release:minor

#1221 Update dependabot conf, group "bedita"
  .github/dependabot.yml
Labels: integration

#1223 Refactor: format date in modules index
  resources/js/app/app.js
  resources/js/app/pages/modules/index.js
Labels: refactor, release:patch
