Repository bedita/manager, pull requests merged in 2025-04, with the labels that each got.

#1258 Calendar in readonly mode
  resources/js/app/components/date-range/date-range.vue
  resources/js/app/components/date-ranges-view/date-ranges-view.vue
  templates/Element/Form/calendar.twig
Labels: feature, Priority - High, release:patch

#1257 Encode placeholder params using utf-8
  resources/js/app/components/placeholder-list/placeholder-list.vue
  resources/js/app/components/placeholder-list/placeholder-params.vue
  resources/js/app/helpers/text-helper.js
  resources/js/app/helpers/view.js
  resources/js/app/plugins/tinymce/placeholders.js
Labels: bug, Priority - Normal, javascript, release:patch

#1259 Avoid error 500 when using multiproject config for API
  src/View/Helper/LayoutHelper.php
  tests/TestCase/View/Helper/LayoutHelperTest.php
Labels: bug, release:patch

#1260 Rename `asciiToBinaryUtf8` and `binaryToAsciiUtf8`
  resources/js/app/components/placeholder-list/placeholder-list.vue
  resources/js/app/components/placeholder-list/placeholder-params.vue
  resources/js/app/components/relation-view/relations-add.js
  resources/js/app/helpers/text-helper.js
  resources/js/app/helpers/view.js
  resources/js/app/plugins/tinymce/placeholders.js
Labels: javascript, refactor

#1262 Index columns for relations related (first object related)
  resources/js/app/components/object-info/object-info.vue
  src/Controller/Component/PropertiesComponent.php
  src/Controller/Component/QueryComponent.php
  templates/Element/Modules/index_table_header.twig
  templates/Element/Modules/index_table_row.twig
  tests/TestCase/Controller/Component/QueryComponentTest.php
Labels: feature, release:patch

#1266 Expandable related items in index cell
  resources/js/app/components/index-cell/index-cell.vue
  templates/Element/Modules/index_table_row.twig
Labels: feature, UI / UX, release:patch

#1264 Module setup for admins
  config/routes.php
  resources/js/app/app.js
  resources/js/app/components/json-editor/json-editor.vue
  resources/js/app/components/module/module-properties.vue
  resources/js/app/components/module/module-setup.vue
  src/Controller/ModulesController.php
  templates/Element/Menu/menu.twig
  templates/Element/Modules/sidebar.twig
  templates/Pages/Modules/setup.twig
  tests/TestCase/Controller/ModulesControllerTest.php
Labels: feature, release:minor
