Repository bedita/manager, pull requests merged in 2025-03, with the labels that each got.

#1236 Fix error in thumbnail retrieval
  composer.json
  tests/TestCase/Controller/ModulesControllerTest.php
  tests/Utils/ModulesControllerSample.php
Labels: bug, Priority - High, release:patch

#1238 Fix modules access control: use BEM roles only
  src/Controller/Component/ModulesComponent.php
Labels: bug, Priority - High, release:patch

#1235 Rich text placeholder params
  config/app_local.example.php
  resources/js/app/components/placeholder-list/placeholder-list.vue
  resources/js/app/components/placeholder-list/placeholder-params.vue
Labels: feature, Priority - Normal, javascript, release:patch

#1239 Fix tinymce richeditor unbind
  resources/js/app/directives/richeditor.js
Labels: bug, UI / UX, release:patch

#1241 Tags api calls return 401 for non admin users
  config/routes.php
  resources/js/app/components/tag-form/tag-form.vue
  resources/js/app/components/tag-picker/tag-picker.vue
  src/Controller/TagsController.php
  tests/TestCase/Controller/TagsControllerTest.php
Labels: bug, release:patch

#1242 Date ranges list in component
  resources/js/app/components/date-ranges-list/date-ranges-list.js
  resources/js/app/components/date-ranges-list/date-ranges-list.vue
  templates/Element/Modules/index_properties_date_ranges.twig
Labels: javascript, refactor, release:patch

#1243 History info vertical scroll
  resources/js/app/components/history/history-info.js
  resources/js/app/components/history/history-info.vue
  templates/Element/Panel/panel.scss
Labels: UI / UX, javascript, refactor, release:patch

#1247 Richeditor configuration for fields from fast create form
  resources/js/app/directives/richeditor.js
Labels: bug, release:patch

#1248 Fix Api controller allowed
  src/Controller/ApiController.php
Labels: bug, Priority - High, release:patch

#1250 Configuration `Upload.uploadMaxSize`
  config/app_local.example.php
  resources/js/app/helpers/view.js
  src/View/Helper/SystemHelper.php
  tests/TestCase/View/Helper/SystemHelperTest.php
Labels: feature, release:patch

#1252 Readonly json fields
  src/View/Helper/PropertyHelper.php
Labels: bug, release:patch

#1254 Related item extra info button
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/app.js
  resources/js/app/components/dialog/dialog.vue
  resources/js/app/components/object-info/object-info.vue
  resources/js/app/components/relation-view/relation-view.vue
  resources/js/app/helpers/view.js
  src/View/Helper/LayoutHelper.php
  src/View/Helper/PropertyHelper.php
  templates/Element/Form/related_item.twig
  tests/TestCase/View/Helper/LayoutHelperTest.php
  tests/TestCase/View/Helper/PropertyHelperTest.php
Labels: feature, release:patch

#1222 Tree preview links + Tree Slug
  config/app_local.example.php
  config/routes.php
  resources/js/app/app.js
  resources/js/app/components/tree-slug/tree-slug.vue
  resources/js/app/components/tree-view/tree-view.vue
  src/Controller/TreeController.php
  templates/Element/Form/trees.twig
  tests/TestCase/Controller/TreeControllerTest.php
Labels: feature

#1253 Add auth providers and external auth modules for admin
  config/i18n_strings.php
  config/routes.php
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  src/Controller/Admin/AdministrationBaseController.php
  src/Controller/Admin/AuthProvidersController.php
  src/Controller/Admin/ExternalAuthController.php
  src/View/Helper/AdminHelper.php
  src/View/Helper/LayoutHelper.php
  templates/Element/Admin/index_content.twig
  templates/Element/Admin/sidebar.twig
  templates/Element/Menu/sidebar.scss
  templates/Pages/Admin/AuthProviders/index.twig
  templates/Pages/Admin/ExternalAuth/index.twig
  tests/TestCase/Controller/Admin/AdministrationBaseControllerTest.php
  tests/TestCase/Controller/Admin/AuthProvidersControllerTest.php
  tests/TestCase/Controller/Admin/ExternalAuthControllerTest.php
  tests/TestCase/View/Helper/AdminHelperTest.php
Labels: feature, Priority - Normal, release:minor

#1255 Restore properties in model object types
  src/Controller/Model/ObjectTypesController.php
  tests/TestCase/Controller/Model/ObjectTypesControllerTest.php
Labels: bug, release:patch

#1256 No MAX_UPLOAD_SIZE in form if -1
  templates/Element/Form/upload.twig
Labels: bug, Priority - High, release:patch
