Repository bedita/manager, pull requests merged in 2025-06, with the labels that each got.

#1280 Fix dependency slevomat coding standard
  composer.json
Labels: bug, dependencies, release:patch

#1279 Skip save when no data changed (advanced)
  src/Controller/Component/ModulesComponent.php
  src/Controller/ModulesController.php
  src/Utility/DateRangesTools.php
  src/Utility/RelationsTools.php
  tests/TestCase/Controller/Component/ModulesComponentTest.php
  tests/TestCase/Controller/ModulesControllerTest.php
  tests/TestCase/Utility/DateRangesToolsTest.php
  tests/TestCase/Utility/RelationsToolsTest.php
Labels: feature, release:patch

#1278 Minimal backporting of tinymce v6 'accordion' plugin
  locales/default.pot
  locales/en_US/default.po
  locales/it_IT/default.po
  resources/js/app/directives/richeditor.js
  resources/js/app/plugins/tinymce/accordion/filter-content.js
  resources/js/app/plugins/tinymce/accordion/plugin.js
  resources/js/app/plugins/tinymce/accordion/utils.js
  resources/richeditor.lazy.scss
Labels: feature, release:minor

#1282 Fix User accesses show last login
  src/Controller/ModulesController.php
Labels: bug, release:patch

#1283 Richtext onchange regex per field + code in toolbar for admins
  config/app_local.example.php
  resources/js/app/directives/richeditor.js
  src/View/Helper/LayoutHelper.php
  src/View/Helper/PermsHelper.php
  src/View/Helper/SchemaHelper.php
  tests/TestCase/View/Helper/LayoutHelperTest.php
  tests/TestCase/View/Helper/SchemaHelperTest.php
Labels: feature, release:minor

#1284 Json properties in module index, avoid truncating
  resources/js/app/components/index-cell/index-cell.vue
  src/View/Helper/PropertyHelper.php
  templates/Element/Modules/index_table_row.twig
Labels: bug, UI / UX, release:patch

#1286 Fix index-cell
  resources/js/app/components/index-cell/index-cell.vue
Labels: bug, release:patch
